import { AuthNavigationService } from './core/auth-navigation.service';
import { MutationIntents } from './core/mutation-intents';
import { SessionService } from './core/session.service';
import { Component, computed, inject, signal } from '@angular/core';
import { HttpErrorResponse } from '@angular/common/http';
import { Router, RouterLink, RouterLinkActive, RouterOutlet, NavigationEnd } from '@angular/router';
import { CdkMenu, CdkMenuItem, CdkMenuItemRadio, CdkMenuTrigger } from '@angular/cdk/menu';
import { filter } from 'rxjs';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ApiService, errorMessage, stateLabel } from './core/api.service';
import { ContextService } from './core/context.service';
import { FeedbackService } from './core/feedback.service';
import { RealtimeService } from './core/realtime.service';
import { ViewStateService } from './core/view-state.service';
import { Account, CurrentUser, Organization, Page } from './core/models';
import { IconComponent } from './shared/icon.component';

@Component({
  selector:'app-root',imports:[RouterOutlet,RouterLink,RouterLinkActive,CdkMenu,CdkMenuItem,CdkMenuItemRadio,CdkMenuTrigger,IconComponent],
  template:`
    <a href="#main" class="skip-link">Перейти к содержимому</a>
    @if(booting()) { <div class="boot"><span class="brand-mark">R</span><p>Открываем рабочее пространство…</p></div> }
    @else if(!context.user()&&authentication.failure()) {
      <main class="public-login"><section class="public-story"><a class="brand" href="/"><img src="favicon.svg" alt="" />repricer</a><div><span class="eyebrow"><app-icon name="sliders" />Рабочее пространство продавца</span><h1>Цены под контролем.<br><span>Без лишней сложности.</span></h1><p>Товары, правила и экономика в одном месте. Понимайте каждое предложение цены до его применения.</p><div class="public-points"><span><app-icon name="box" />Понятные предложения цены</span><span><app-icon name="shield" />Проверки перед применением</span><span><app-icon name="history" />История решений и изменений</span></div></div><small>© {{year}} repricer</small></section><section class="public-access"><div><h2>Не удалось завершить вход</h2><div class="notice error" role="alert">{{authentication.failure()}}</div><button class="btn primary large" (click)="authentication.signIn(true)">Повторить вход<app-icon name="arrow" /></button><p class="muted">Защищённый вход в ваше рабочее пространство.</p></div></section></main>
    }
    @else if(context.user()) {
      <div class="app-shell">
        <aside class="sidebar" [class.mobile-open]="mobileOpen()"><a class="brand" routerLink="/products"><img src="favicon.svg" alt="" />repricer</a><nav aria-label="Основная навигация"><div class="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div>@for(item of workspaceNav;track item.route){<a class="nav-item" [routerLink]="item.route" [class.active]="activeSection()===item.section" (click)="mobileOpen.set(false)"><app-icon [name]="item.icon" /><span>{{item.label}}</span></a>}<div class="nav-label company-label">КОМПАНИЯ</div><a class="company-link" routerLink="/organization"><app-icon name="building" /><span>{{context.organization()?.name || 'Выбрать компанию'}}</span><app-icon name="chevron" /></a>@for(item of companyNav;track item.route){<a class="nav-item" [routerLink]="item.route" routerLinkActive="active" (click)="mobileOpen.set(false)"><app-icon [name]="item.icon" /><span>{{item.label}}</span></a>}</nav></aside>
        @if(mobileOpen()){<button class="mobile-backdrop" aria-label="Закрыть меню" (click)="mobileOpen.set(false)"></button>}
        <div class="workspace-shell"><div class="workspace-path"><nav aria-label="Хлебные крошки"><a [routerLink]="breadcrumbRoot()">{{activeSection()}}</a>@if(pageTitle()!==activeSection()){<app-icon name="chevron" /><span aria-current="page">{{pageTitle()}}</span>}</nav><a class="icon-button" routerLink="/help" title="Помощь" aria-label="Помощь"><app-icon name="info" /></a></div>
          <header class="topbar"><button class="icon-button mobile-menu" (click)="mobileOpen.set(true)" aria-label="Открыть меню"><app-icon name="menu" /></button><button class="account-control" [cdkMenuTriggerFor]="accountMenu" aria-label="Выбрать кабинет"><app-icon name="store" /><span>{{context.account()?.name || 'Выберите кабинет'}}</span>@if(context.account();as account){<img class="market-logo" [src]="account.marketplace==='OZON'?'ozon.svg':'yandex.svg'" [alt]="account.marketplace==='OZON'?'Ozon':'Яндекс Маркет'">}<app-icon name="down" /></button><span class="spacer"></span><a class="icon-button" routerLink="/notifications" aria-label="События" title="События"><app-icon name="bell" /></a><span class="top-separator"></span><button class="profile-trigger" [cdkMenuTriggerFor]="profileMenu" aria-label="Открыть меню профиля"><span class="avatar">{{initials()}}</span><app-icon name="down" /></button></header>
          @if(context.organization()&&realtime.state()!=='current'){<div class="connection-state" [class.offline]="realtime.state()==='offline'"><app-icon name="clock" /><span>{{realtime.state()==='offline'?'Связь потеряна. Данные могут быть неактуальны.':realtime.state()==='connecting'?'Подключаем обновления…':'Восстанавливаем актуальность данных…'}}</span>@if(realtime.state()==='offline'){<button class="link" (click)="realtime.retry()">Повторить подключение</button>}</div>}
          @if(session.accessError()){<div class="notice error" role="alert">{{session.accessError()}}<button class="btn" (click)="session.refreshAccess()">Обновить права</button></div>}
          @if(error()){<div class="notice error" role="alert">{{error()}}<button class="btn" (click)="loadAccounts()">Повторить</button></div>}
          <main class="content" id="main" tabindex="-1"><router-outlet /></main><footer class="app-footer"><span>© {{year}} <strong>repricer</strong></span><nav><a routerLink="/help">Помощь</a><a routerLink="/about">О приложении</a></nav></footer>
        </div>
      </div>
      <ng-template #accountMenu><div cdkMenu class="anchored-menu account-menu"><div class="popup-heading"><strong>Кабинет</strong><small>{{context.organization()?.name}}</small></div>@for(account of context.accounts();track account.id){<button cdkMenuItemRadio [cdkMenuItemChecked]="context.account()?.id===account.id" (cdkMenuItemTriggered)="selectAccount(account)" class="account-option"><app-icon name="store" /><span><strong>{{account.name}} <img class="market-logo" [src]="account.marketplace==='OZON'?'ozon.svg':'yandex.svg'" [alt]="account.marketplace==='OZON'?'Ozon':'Яндекс Маркет'"></strong><small>{{label(account.status)}}</small></span>@if(context.account()?.id===account.id){<app-icon name="check" />}</button>}@empty{<p class="menu-empty">Нет подключённых кабинетов</p>}@if(context.accountsTotal()>50){<div class="pagination"><button cdkMenuItem class="btn" [disabled]="context.accountsPage()===0" (click)="changeAccountPage(-1)">Назад</button><span>{{context.accountsPage()+1}} · {{context.accountsTotal()}}</span><button cdkMenuItem class="btn" [disabled]="(context.accountsPage()+1)*50>=context.accountsTotal()" (click)="changeAccountPage(1)">Далее</button></div>}<a cdkMenuItem routerLink="/accounts" class="menu-footer"><app-icon name="store" />Управление кабинетами<app-icon name="chevron" /></a></div></ng-template>
      <ng-template #profileMenu><div cdkMenu class="anchored-menu profile-menu"><div class="profile-summary"><span class="avatar">{{initials()}}</span><div><strong>{{context.user()?.displayName}}</strong><small>{{context.user()?.email}}</small></div></div><a cdkMenuItem routerLink="/profile"><app-icon name="user" />Мой профиль</a><a cdkMenuItem routerLink="/organization"><app-icon name="building" />{{context.organization()?.name || 'Компания'}}</a><a cdkMenuItem routerLink="/start"><app-icon name="store" />Сменить компанию</a><button cdkMenuItem class="logout" (cdkMenuItemTriggered)="logout()"><app-icon name="logout" />Выйти из системы</button></div></ng-template>
    }
    @if(feedback.message();as message){<aside class="toast" [class.error]="message.error" [attr.role]="message.error?'alert':'status'" (pointerenter)="feedback.pause()" (focusin)="feedback.pause()"><app-icon [name]="message.error?'alert':'check'" /><span>{{message.text}}</span><button class="icon-button" aria-label="Закрыть сообщение" (click)="feedback.close()"><app-icon name="close" /></button></aside>}
  `,
})
export class AppComponent {
  readonly authentication=inject(AuthNavigationService);readonly context=inject(ContextService);readonly realtime=inject(RealtimeService);readonly feedback=inject(FeedbackService);
  private readonly intents=inject(MutationIntents);readonly session=inject(SessionService);private readonly api=inject(ApiService);private readonly router=inject(Router);private readonly viewState=inject(ViewStateService);
  readonly booting=signal(true);readonly error=signal('');readonly mobileOpen=signal(false);readonly route=signal('products');readonly label=stateLabel;readonly year=new Date().getFullYear();
  readonly workspaceNav=[{route:'/products',label:'Операции',icon:'box',section:'Операции'},{route:'/analytics',label:'Аналитика',icon:'chart',section:'Аналитика'},{route:'/competitors',label:'Конкуренты',icon:'search',section:'Конкуренты'},{route:'/integration',label:'Интеграция',icon:'plug',section:'Интеграция'},{route:'/account-team',label:'Доступ к кабинету',icon:'users',section:'Доступ к кабинету'},{route:'/account-audit',label:'Аудит кабинета',icon:'history',section:'Аудит кабинета'}];
  readonly companyNav=[{route:'/accounts',label:'Кабинеты',icon:'store'},{route:'/team',label:'Команда и доступ',icon:'users'},{route:'/audit',label:'Аудит компании',icon:'history'}];
  readonly initials=computed(()=>this.context.user()?.displayName.split(/\s+/).filter(Boolean).slice(0,2).map(value=>value[0]).join('').toUpperCase()??'');
  readonly pageTitle=computed(()=>{const labels:Record<string,string>={products:'Товары',automation:'Автоматизация',analytics:'Обзор',finance:'Начисления',payments:'Выплаты',expenses:'Расходы и налог',units:'Экономика товаров',inventory:'Запасы',returns:'Возвраты',outlook:'Ориентир при текущих условиях',competitors:'Конкуренты',integration:'Интеграция',organization:this.context.organization()?.name??'Компания',accounts:'Кабинеты',team:'Команда и доступ',invitations:'Приглашения',audit:'Аудит компании','account-team':'Доступ к кабинету','account-audit':'Аудит кабинета',profile:'Профиль',notifications:'Уведомления',insights:'Инсайты',alerts:'Алерты',tasks:'Фоновые задачи',imports:'История импорта',reports:'История экспорта',start:'Рабочие пространства',decisions:'Детали решения',commands:'Команда',help:'Помощь',about:'О приложении'};return labels[this.route()]??'Страница не найдена';});
  readonly activeSection=computed(()=>{const route=this.route();if(['products','automation','decisions','commands'].includes(route))return'Операции';if(['analytics','finance','payments','expenses','units','inventory','returns','outlook'].includes(route))return'Аналитика';if(['organization','accounts','team','invitations','audit','start'].includes(route))return'Компания';if(['notifications','insights','alerts','tasks','imports','reports'].includes(route))return'События';return this.pageTitle();});
  readonly breadcrumbRoot=computed(()=>this.activeSection()==='Операции'?'/products':this.activeSection()==='Аналитика'?'/analytics':this.activeSection()==='Компания'?'/organization':'/'+this.route());
  constructor(){const invitation=new URLSearchParams(location.hash.slice(1)).get('invitation');if(invitation&&invitation.length<=256){sessionStorage.setItem('repricer.invitation',invitation);history.replaceState(null,'',location.pathname+location.search);}this.router.events.pipe(filter(event=>event instanceof NavigationEnd),takeUntilDestroyed()).subscribe(()=>{this.route.set(this.router.url.split('/')[1]?.split('?')[0]||'products');this.mobileOpen.set(false);document.title=this.pageTitle()+' · repricer';});void this.bootstrap();}
  private async bootstrap():Promise<void>{try{let user=await this.api.getMe();this.authentication.authenticated();await this.api.getCsrf();const invitation=sessionStorage.getItem('repricer.invitation');if(invitation){try{await this.api.acceptInvitation({body:{clientRequestId:crypto.randomUUID(),token:invitation}});sessionStorage.removeItem('repricer.invitation');user=await this.api.getMe();}catch(error:unknown){this.error.set(errorMessage(error));}}this.context.user.set(user);if(user.organizations.length===1){this.context.selectOrganization(user.organizations[0]);await this.loadAccounts();}else{await this.router.navigateByUrl('/start');}}catch(error:unknown){if(!(error instanceof HttpErrorResponse)||error.status!==401){this.error.set(errorMessage(error));this.authentication.failure.set(errorMessage(error));}}finally{this.booting.set(false);}}
  async loadAccounts():Promise<void>{this.error.set('');try{await this.session.loadAccounts();}catch(error:unknown){this.error.set(errorMessage(error));}}
  async changeAccountPage(delta:number):Promise<void>{try{await this.session.loadAccounts(Math.max(0,this.context.accountsPage()+delta));}catch(error:unknown){this.error.set(errorMessage(error));}}
  async selectAccount(account:Account):Promise<void>{this.error.set('');try{await this.session.selectAccount(account);}catch(error:unknown){this.error.set(errorMessage(error));}}
  async logout():Promise<void>{this.error.set('');try{const result=await this.api.logout();this.viewState.clear();this.intents.clear();this.context.clear();location.assign(result.redirectUrl);}catch{this.feedback.show('Не удалось завершить сессию. Повторите выход.',true);}}
}
