import { DailyIncomeComponent } from './daily-income.component';
import { ViewStateService, initialView } from '../core/view-state.service';
import { ViewState } from '../core/models';
import { ViewRefresh } from '../core/view-refresh';
import { Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ApiService, decimal, errorMessage } from '../core/api.service';
import { ContextService } from '../core/context.service';
import { RealtimeService } from '../core/realtime.service';
import { EconomicsSummary } from '../core/models';
import { IconComponent } from '../shared/icon.component';
import { MatDialog } from '@angular/material/dialog';
import { ExportDialogComponent } from '../shared/workflow-dialogs';
import { FeedbackService } from '../core/feedback.service';

@Component({selector:'app-analytics',imports:[FormsModule,RouterLink,IconComponent,DailyIncomeComponent],template:`
  <h1 class="sr-only">Месячный результат</h1><nav class="tabs"><a routerLink="/analytics" class="active">Обзор</a><a routerLink="/finance">Финансы</a><a routerLink="/units">Товары и запасы</a><a routerLink="/outlook">Ориентир при текущих условиях</a></nav><div class="section-bar"><label class="period-label">Период <input type="month" [ngModel]="period()" (ngModelChange)="changePeriod($event)" [disabled]="!viewReady()"></label><span class="muted">Месячная финансовая публикация</span><span class="spacer"></span>@if(canExport()){<button class="btn" [disabled]="!viewReady()" (click)="exportReport()"><app-icon name="download" />Подготовить отчёт</button>}<a class="btn quiet" routerLink="/reports">История экспорта</a></div>
  @if(viewStore.status()){<div class="notice">{{viewStore.status()}} @if(viewStore.conflict()){<button class="btn" (click)="viewStore.resolveConflict()">Применить мой период</button>}@else{<button class="btn" (click)="viewStore.retry()">Повторить сохранение</button>}</div>}
  @if(error()){<div class="notice error" role="alert">{{error()}}<button class="btn" (click)="load()">Повторить</button></div>}
  @if(summary();as result){<div class="metric-grid"><div class="metric"><span>Доход после возвратов</span><strong>{{money(result.revenue)}}</strong><small>По финансовой публикации</small></div><div class="metric"><span>Себестоимость</span><strong>{{money(result.costs)}}</strong><small>Разрешённые данные учёта</small></div><div class="metric"><span>Месячный результат</span><strong>{{money(result.result)}}</strong><small>Не расчётная прибыль товара</small></div><div class="metric"><span>Полнота источников</span><strong class="completeness">{{result.completeness}}</strong><small>{{result.period}}</small></div></div><div class="cols-2"><section class="panel"><header class="panel-head"><app-icon name="chart" /><h2>Структура результата по включённым расходам</h2></header><div class="panel-body">@for(line of result.lines;track line.id){<div class="data-pair"><span>{{line.name}}</span><strong>{{money(line.amount)}}</strong></div>}@empty{<p class="muted">Структура публикации ещё не получена.</p>}@for(section of result.sections;track section.id){<details><summary>{{section.name}} · {{section.events}} событий</summary>@for(line of section.lines;track line.id){<div class="data-pair"><span>{{line.name}}</span><strong>{{money(line.amount)}}</strong></div>}</details>}</div></section><section class="panel"><header class="panel-head"><app-icon name="info" /><h2>Основание и полнота</h2></header><div class="panel-body"><div class="data-pair"><span>Период</span><strong>{{result.period}}</strong></div><div class="data-pair"><span>Состояние</span><strong>{{result.status}}</strong></div>@for(reason of result.unknownReasons;track reason){<div class="notice">{{reason}}</div>}<p class="inline-note">Начисления и подтверждённые движения денег показаны отдельно. Неизвестные компоненты не подменяются нулём.</p><a class="btn quiet" routerLink="/finance" [queryParams]="{month:result.period}">Открыть начисления<app-icon name="arrow" /></a></div></section></div><app-daily-income [days]="result.daily" />}@else if(!error()){<section class="panel empty"><app-icon name="chart" /><h2>{{loading()?'Загружаем финансовую публикацию…':'Выберите кабинет'}}</h2><p>Итоги рассчитывает сервер по подтверждённым источникам выбранного периода.</p></section>}
`,styles:`.period-label{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--muted)}.period-label input{border:1px solid #c4cad3;border-radius:7px;padding:8px 10px;background:white;color:var(--text)}.completeness{font-size:18px!important;line-height:1.5}`})
export class AnalyticsComponent {
  private readonly reads = new ViewRefresh(inject(DestroyRef));
  private readonly dialogs=inject(MatDialog);private readonly feedback=inject(FeedbackService);

  private readonly api=inject(ApiService);private readonly context=inject(ContextService);private readonly realtime=inject(RealtimeService);readonly viewStore=inject(ViewStateService);readonly viewReady=signal(false);private savedView:ViewState=initialView();readonly period=signal('');readonly summary=signal<EconomicsSummary|null>(null);readonly loading=signal(false);readonly error=signal('');readonly money=decimal;private epoch=0;private unsubscribe?:()=>void;
  constructor(){effect(()=>{this.context.identity();this.context.permissions();void this.activate();});inject(DestroyRef).onDestroy(()=>{this.epoch++;this.unsubscribe?.();});}
  private async activate():Promise<void>{const epoch=++this.epoch;this.viewReady.set(false);this.summary.set(null);this.unsubscribe?.();if(!this.context.account())return;this.loading.set(true);try{const state=await this.viewStore.open('analytics');if(epoch!==this.epoch)return;this.savedView=state;this.period.set(state.query.filters['month']??initialView('analytics',this.context.account()?.timezone??'UTC').query.filters['month']);this.viewReady.set(true);this.unsubscribe=this.realtime.subscribe(['economics/accruals','economics/summary'],async()=>{await this.load();return !this.error();},false,{owner:this.reads,key:'load'});}catch(error:unknown){if(epoch===this.epoch){this.error.set(errorMessage(error));this.loading.set(false);}}}
  changePeriod(value:string):void{if(!/^[1-9][0-9]{3}-(0[1-9]|1[0-2])$/.test(value))return;this.period.set(value);this.savedView={...this.savedView,query:{...this.savedView.query,filters:{month:value}}};this.viewStore.save(this.savedView);void this.load();}
  canExport():boolean{return this.context.allows('finance.read')&&this.context.allows('export');}
  exportReport():void{const organization=this.context.organization(),account=this.context.account();if(!organization||!account||!this.viewReady()||!this.canExport())return;this.dialogs.open(ExportDialogComponent,{width:'620px',data:{monthly:true,resource:'monthly-pnl',query:{...this.savedView.query,search:'',filters:{month:this.period()},page:0},ids:[],requestScope:{organizationId:organization.id,accountId:account.id}}}).afterClosed().subscribe(created=>{if(created)this.feedback.show('Отчёт принят. Состояние и файл доступны в истории экспорта.');});}
  load():Promise<void>{this.epoch++;return this.reads.run('load',()=>this.loadCurrent(),()=>!this.error());}
  private async loadCurrent():Promise<void>{if(!this.context.account()||!this.viewReady())return;const epoch=++this.epoch;this.loading.set(true);this.error.set('');try{const result=await this.api.getEconomicsSummary({query:{"period":this.period()}});if(epoch===this.epoch){this.summary.set(result);}}catch(error:unknown){if(epoch===this.epoch)this.error.set(errorMessage(error));}finally{if(epoch===this.epoch)this.loading.set(false);}}
}
