import { ViewRefresh } from '../core/view-refresh';
import { Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { firstValueFrom } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { ApiService, dateTime, decimal, percentage, errorMessage, mutation, stateLabel } from '../core/api.service';
import { ContextService } from '../core/context.service';
import { FeedbackService } from '../core/feedback.service';
import { RealtimeService } from '../core/realtime.service';
import { Command, Decision } from '../core/models';
import { ConfirmDialogComponent } from '../shared/dialogs';
import { IconComponent } from '../shared/icon.component';
import { QuantityComparisonComponent } from '../shared/quantity-comparison.component';

@Component({selector:'app-decision',imports:[RouterLink,IconComponent,QuantityComparisonComponent],template:`
  @if(error()){<div class="notice error" role="alert">{{error()}}<button class="btn" (click)="load()">Повторить</button></div>}
  @if(decision();as result){<h1 class="sr-only">Детали решения</h1><div class="section-bar"><div><h2>{{result.offerName || result.offerId}}</h2><p class="inline-note">{{result.id}} · {{date(result.createdAt)}}</p></div><a class="btn quiet" [routerLink]="['/products',result.offerId,'automation']">К автоматизации товара<app-icon name="arrow" /></a></div><div class="metric-grid"><div class="metric"><span>Цена продавца</span><strong>{{money(result.currentPrice)}}</strong><small>Снимок входов решения</small></div><div class="metric"><span>Предложение</span><strong>{{money(result.proposedPrice)}}</strong><small>Сохранённый расчёт</small></div>@if(context.allows('finance.read')){<div class="metric"><span>Прибыль расчёта</span><strong>{{money(result.profit)}}</strong><small>Не фактический результат продаж</small></div>}<div class="metric"><span>Состояние</span><strong class="status-value">{{label(result.status)}}</strong><small>Версия правила {{result.policyVersion}}</small></div></div>
    <div class="cols-2"><section class="panel"><header class="panel-head"><app-icon name="sliders" /><h2>Сохранённый результат</h2></header><div class="panel-body"><div class="data-pair"><span>Способ выбора цены</span><strong>{{result.strategy}}</strong></div><div class="data-pair"><span>Версия политики</span><strong>{{result.policyVersion}}</strong></div>@if(context.allows('finance.read')){<div class="data-pair"><span>Маржа</span><strong>{{percent(result.margin)}}</strong></div>}@for(reason of result.reasons;track reason){<div class="notice">{{reason}}</div>}<p class="inline-note">Текущее назначение товара не подменяет историческое основание этого решения.</p></div></section>@if(context.allows('finance.read')){<app-quantity-comparison [decision]="result" />}</div><section class="panel"><header class="panel-head"><app-icon name="history" /><h2>Полный план действий</h2></header><div class="panel-body">@for(step of result.steps;track step.id){<article class="plan-step"><span><app-icon name="chevron" /></span><div><strong>{{step.type}}</strong><p>{{step.description}}</p></div><span class="badge">{{label(step.status)}}</span></article>}@empty{<p class="muted">Сохранённый план не содержит шагов исполнения.</p>}@if(result.commandId){<a class="btn" [routerLink]="['/commands',result.commandId]">Открыть связанную команду</a>}@if(context.allows('decision.approve')&&result.status==='CALCULATED'){<div class="page-actions"><button class="btn primary" [disabled]="busy()" (click)="approve()">Подтвердить полный план</button></div>}</div></section>
  }
  @if(command();as result){<div class="section-bar"><div><h2>Команда {{result.id}}</h2><p class="inline-note">{{date(result.createdAt)}} · {{label(result.status)}}</p></div><a class="btn quiet" [routerLink]="['/decisions',result.decisionId]">Основание решения<app-icon name="arrow" /></a></div><section class="panel"><div class="panel-body"><div class="data-pair"><span>Целевое значение</span><strong>{{money(result.targetPrice)}}</strong></div><div class="data-pair"><span>Состояние подтверждения</span><strong>{{label(result.status)}}</strong></div>@if(result.status==='UNKNOWN'){<div class="notice"><app-icon name="alert" /><span>Результат внешней отправки неизвестен. Повторная SEND не выполняется. Требуется сверка.</span></div>}@for(step of result.effects;track step.id){<article class="plan-step"><app-icon name="clock" /><div><strong>{{step.type}}</strong><p>{{step.description}}</p></div><span class="badge">{{label(step.status)}}</span></article>}<h3 class="section-title">Попытки и подтверждения</h3>@for(attempt of result.attempts;track attempt.id){<div class="data-pair"><span>{{date(attempt.startedAt)}}</span><strong>{{label(attempt.outcome)}}{{attempt.message?' · '+attempt.message:''}}</strong></div>}@empty{<p class="inline-note">Подтверждённых попыток отправки пока нет.</p>}<div class="page-actions">@if(context.allows('command.reconcile')){<button class="btn" [disabled]="busy()" (click)="commandAction('reconcile')">Запросить сверку</button>}@if(result.status==='PENDING'&&context.allows('automation.pause')){<button class="btn" [disabled]="busy()" (click)="commandAction('cancel')">Отменить неотправленную команду</button>}</div></div></section>}
  @if(!decision()&&!command()&&!error()){<section class="panel empty"><app-icon name="history" /><h2>Загружаем сохранённый результат…</h2></section>}
`,styles:`.status-value{font-size:18px!important}.plan-step{display:flex;align-items:flex-start;gap:15px;padding:17px 0;border-bottom:1px solid var(--line);font-size:12px}.plan-step>div{flex:1}.plan-step p{color:var(--muted);font-size:12px;margin-top:5px}.plan-step>app-icon{color:var(--muted)}.section-title{margin:24px 0 14px}`})
export class DecisionComponent {
  private readonly reads = new ViewRefresh(inject(DestroyRef));

  readonly context=inject(ContextService);private readonly api=inject(ApiService);private readonly realtime=inject(RealtimeService);private readonly feedback=inject(FeedbackService);private readonly dialog=inject(MatDialog);private readonly route=inject(ActivatedRoute);private readonly params=toSignal(this.route.paramMap);private readonly data=toSignal(this.route.data);readonly decision=signal<Decision|null>(null);readonly command=signal<Command|null>(null);readonly error=signal('');readonly busy=signal(false);readonly date=(value:string|undefined)=>dateTime(value,this.context.account()?.timezone??'UTC');readonly money=decimal;readonly percent=percentage;readonly label=stateLabel;private epoch=0;private unsubscribe?:()=>void;
  constructor(){effect(()=>{this.context.identity();this.context.permissions();this.params();this.data();this.epoch++;this.decision.set(null);this.command.set(null);this.unsubscribe?.();if(this.context.account())this.unsubscribe=this.realtime.subscribe(['decisions','commands'],async()=>{await this.load();return !this.error();},false,{owner:this.reads,key:'load'});});inject(DestroyRef).onDestroy(()=>{this.epoch++;this.unsubscribe?.();});}
  load():Promise<void>{this.epoch++;return this.reads.run('load',()=>this.loadCurrent(),()=>!this.error());}
  private async loadCurrent():Promise<void>{const id=this.params()?.get('id');if(!id)return;const epoch=++this.epoch;this.error.set('');try{if(this.data()?.['mode']==='command'){const command=await this.api.getCommand({path:{id:id}});if(epoch===this.epoch)this.command.set(command);}else{const decision=await this.api.getDecision({path:{id:id}});if(epoch===this.epoch)this.decision.set(decision);}}catch(error:unknown){if(epoch===this.epoch)this.error.set(errorMessage(error));}}
  async approve():Promise<void>{const decision=this.decision();if(!decision||this.busy())return;const confirmed:boolean|undefined=await firstValueFrom(this.dialog.open(ConfirmDialogComponent,{width:'620px',data:{title:'Подтвердить полный план?',message:'Подтверждение относится только к этому решению, его входным редакциям и всем перечисленным шагам. Перед отправкой сервер повторно проверит доступ и ограничения.',action:'Подтвердить план'}}).afterClosed());if(!confirmed)return;this.busy.set(true);try{await this.api.approveDecision({path:{id:decision.id},body:mutation(decision.revision)});this.feedback.show('Подтверждение принято. Применение будет показано отдельно после проверки площадкой.');}catch(error:unknown){this.feedback.show(errorMessage(error),true);}finally{this.busy.set(false);}}
  async commandAction(action:'reconcile'|'cancel'):Promise<void>{const command=this.command();if(!command||this.busy())return;this.busy.set(true);try{await (action==='reconcile'?this.api.reconcileCommand({path:{id:command.id},body:mutation(command.revision)}):this.api.cancelCommand({path:{id:command.id},body:mutation(command.revision)}));this.feedback.show(action==='reconcile'?'Сверка принята. Повторной отправки команды нет.':'Запрос отмены принят. Результат проверяется сервером.');}catch(error:unknown){this.feedback.show(errorMessage(error),true);}finally{this.busy.set(false);}}
}
