import { ViewRefresh } from '../core/view-refresh';
import { Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink, RouterLinkActive } from '@angular/router';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ApiService, dateTime, errorMessage, mutation } from '../core/api.service';
import { ContextService } from '../core/context.service';
import { RealtimeService } from '../core/realtime.service';
import { Notification, Page } from '../core/models';
import { IconComponent } from '../shared/icon.component';

@Component({selector:'app-events',imports:[RouterLink,RouterLinkActive,IconComponent],template:`
  <h1 class="sr-only">События</h1><div class="page-toolbar"><nav class="page-tabs" aria-label="События"><a routerLink="/notifications" routerLinkActive="active">Уведомления</a><a routerLink="/insights" routerLinkActive="active">Инсайты</a><a routerLink="/alerts" routerLinkActive="active">Алерты</a><a routerLink="/tasks">Фоновые задачи</a></nav><button class="btn quiet" (click)="readAll()" [disabled]="busy()||loading()">Прочитать все</button></div>
  @if(error()){<div class="notice error" role="alert">{{error()}}<button class="btn" (click)="load()">Повторить</button></div>}
  @if(loading()){<div class="loading" role="status">Загружаем события…</div>}
  @else if(!context.organization()){<div class="empty"><h2>Выберите компанию</h2><a class="btn" routerLink="/start">Открыть компании</a></div>}
  @else if(!error()){<section class="panel event-list">@for(item of items();track item.id){<article class="event-item" [class.unread]="!item.read"><span class="event-icon"><app-icon [name]="item.category==='ALERT'?'alert':item.category==='INSIGHT'?'chart':'bell'" /></span><div><strong>{{item.title}}</strong><p>{{item.message}}</p><small>{{date(item.createdAt)}}</small>@if(target(item);as link){<a [routerLink]="link" class="link">Открыть основание</a>}</div><span class="spacer"></span>@if(!item.read){<button class="icon-button" title="Отметить прочитанным" aria-label="Отметить прочитанным" (click)="markRead(item)" [disabled]="busy()"><app-icon name="check" /></button>}</article>}@empty{<div class="empty"><app-icon name="bell" /><h2>Новых событий нет</h2><p>Здесь появятся уведомления о работе выбранного кабинета.</p></div>}</section><div class="pagination"><span>{{total()}} событий</span><button class="btn" [disabled]="page()===0||loading()" (click)="changePage(-1)">Назад</button><span>Страница {{page()+1}}</span><button class="btn" [disabled]="(page()+1)*50>=total()||loading()" (click)="changePage(1)">Далее</button></div>}
`})
export class EventsComponent {
  private readonly reads = new ViewRefresh(inject(DestroyRef));

  readonly context=inject(ContextService);private readonly api=inject(ApiService);private readonly realtime=inject(RealtimeService);private readonly route=inject(ActivatedRoute);private readonly destroy=inject(DestroyRef);
  readonly mode=signal('notifications');readonly items=signal<Notification[]>([]);readonly total=signal(0);readonly page=signal(0);readonly error=signal('');readonly loading=signal(false);readonly busy=signal(false);readonly date=(value:string|undefined)=>dateTime(value,this.context.account()?.timezone??'UTC');private epoch=0;
  constructor(){this.route.data.pipe(takeUntilDestroyed()).subscribe(data=>{this.mode.set(String(data['mode']??'notifications'));this.page.set(0);});effect(onCleanup=>{this.context.identity();this.context.permissions();this.mode();this.epoch++;this.items.set([]);if(!this.context.organization())return;const stop=this.realtime.subscribe(['notifications'],async()=>{await this.load();return !this.error();},false,{owner:this.reads,key:'load'});onCleanup(stop);});this.destroy.onDestroy(()=>this.epoch++);}
  load():Promise<void>{this.epoch++;return this.reads.run('load',()=>this.loadCurrent(),()=>!this.error());}
  private async loadCurrent():Promise<void>{const epoch=++this.epoch;this.loading.set(true);this.error.set('');try{const result=await this.api.listNotifications({query:{"category":this.mode()==='alerts'?'ALERT':this.mode()==='insights'?'INSIGHT':'NOTIFICATION',"page":this.page(),"size":50}});if(epoch!==this.epoch)return;this.items.set(result.items);this.total.set(result.total);}catch(error:unknown){if(epoch===this.epoch)this.error.set(errorMessage(error));}finally{if(epoch===this.epoch)this.loading.set(false);}}
  changePage(delta:number):void{this.page.update(page=>page+delta);void this.load();}
  target(item:Notification):string|null{const routes:Record<string,string>={DECISION:'decisions',COMMAND:'commands',OFFER:'products'};return item.resourceType&&item.resourceId&&routes[item.resourceType]?`/${routes[item.resourceType]}/${encodeURIComponent(item.resourceId)}`:null;}
  async markRead(item:Notification):Promise<void>{if(this.busy())return;this.busy.set(true);try{const updated=await this.api.readNotification({path:{id:item.id},body:mutation(item.revision)});this.items.update(items=>items.map(value=>value.id===updated.id?updated:value));}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.busy.set(false);}}
  async readAll():Promise<void>{if(this.busy())return;this.busy.set(true);try{await this.api.readAllNotifications({body:mutation()});await this.load();}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.busy.set(false);}}
}

@Component({selector:'app-help',imports:[RouterLink,IconComponent],template:`
  <section class="panel document-panel">@switch(mode){@case('help'){<span class="eyebrow">Помощь</span><h1>Работа с repricer</h1><h2>Подключите кабинет</h2><p>В разделе «Кабинеты» добавьте магазин и ключ API, затем проверьте соединение на странице интеграции. Статус каждого источника показывает доступность и время последнего успешного обновления.</p><a routerLink="/accounts">Открыть кабинеты →</a><h2>Проверьте данные товара</h2><p>Для расчёта нужны цена, себестоимость, тарифы и актуальные условия площадки. Отсутствующие основания показываются явно. Наблюдаемая цена покупателя сама по себе не означает управляемую цену продавца.</p><h2>Настройте политику</h2><p>Обычное правило, ограничения и назначение задаются отдельно. Начните с расчёта без применения. Автоматическая работа требует отдельного допуска для назначения.</p><a routerLink="/automation">Открыть автоматизацию →</a><h2>Проверяйте результат</h2><p>У решения есть сохранённые основания, проверки и план действий. Подтверждение относится ко всему плану. Неизвестный результат команды требует сверки с площадкой, а не повторной отправки.</p><h2>Аналитика</h2><p>Расчётная прибыльность, фактические начисления и денежные выплаты показаны раздельно. Ориентир при текущих условиях не является прогнозом спроса.</p>}@case('about'){<img src="favicon.svg" alt="" width="48" height="48"><h1>repricer</h1><p>Рабочее пространство для управления ценами и экономикой продавца.</p><p>Данные, расчёты, проверки безопасности и история изменений сохраняются в контексте компании и кабинета.</p>}@default{<app-icon name="search" /><h1>Страница не найдена</h1><p>Проверьте адрес или вернитесь к товарам.</p><a class="btn primary" routerLink="/products">Открыть товары</a>}}</section>
`})
export class HelpComponent {readonly mode=String(inject(ActivatedRoute).snapshot.data['mode']??'help');}
