import { UnsavedChangesService } from '../shared/unsaved-changes';
import { Component, DestroyRef, HostListener, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { ApiService, errorMessage, mutation, stateLabel } from '../core/api.service';
import { ContextService } from '../core/context.service';
import { SessionService } from '../core/session.service';
import { Organization } from '../core/models';
import { IconComponent } from '../shared/icon.component';

@Component({selector:'app-organization',imports:[FormsModule,RouterLink,IconComponent],template:`
  @if(error()){<div class="notice error" role="alert">{{error()}}</div>}
  @if(mode()==='start') {
    <div class="section-bar"><h1>Рабочие пространства</h1><button class="btn" (click)="creating.set(true)"><app-icon name="plus" />Создать компанию</button></div><p class="inline-note">Выберите компанию для продолжения работы.</p>
    @for(organization of context.user()?.organizations;track organization.id){<section class="panel company-card"><span class="company-symbol"><app-icon name="building" /></span><div><h2>{{organization.name}}</h2><p>{{label(organization.role)}}</p></div><button class="btn primary" [disabled]="saving()" (click)="select(organization)">Открыть компанию<app-icon name="arrow" /></button></section>}
    @if(creating()){<section class="panel"><form class="panel-body" (ngSubmit)="create()"><h2>Новая компания</h2><label class="field">Название<input name="companyName" [(ngModel)]="name" required maxlength="80"></label><div class="page-actions"><button class="btn" type="button" (click)="cancelEdit()">Отмена</button><button class="btn primary" type="submit" [disabled]="saving()">Создать компанию</button></div></form></section>}
    <section class="panel"><div class="panel-body"><h2>Приглашение в компанию</h2><p class="inline-note">Откройте ссылку из приглашения или введите его код.</p><form (ngSubmit)="acceptInvitation()"><label class="field">Код приглашения<input name="invitation" [(ngModel)]="invitationToken" required autocomplete="off"></label><button class="btn" type="submit" [disabled]="saving()">Принять приглашение</button></form></div></section>
  } @else if(mode()==='profile') {
    <h1 class="sr-only">Мой профиль</h1><section class="panel"><div class="panel-body"><div class="profile-heading"><span class="avatar large">{{initials()}}</span><div><h2>{{context.user()?.displayName}}</h2><p class="muted">{{context.user()?.email}}</p></div></div><div class="data-pair"><span>Идентификатор пользователя</span><strong>{{context.user()?.userId}}</strong></div><div class="data-pair"><span>Текущая компания</span><strong>{{context.organization()?.name || 'Не выбрана'}}</strong></div><p class="inline-note">Аутентификация и пароль управляются единым провайдером входа. Рабочие права проверяются отдельно в каждой компании и кабинете.</p></div></section>
  } @else {
    <h1 class="sr-only">Компания</h1><div class="page-actions"><a class="btn" routerLink="/start"><app-icon name="building" />Сменить компанию<app-icon name="chevron" /></a></div>
    @if(context.organization();as organization){<section class="panel company-identity"><div class="company-card"><span class="company-symbol"><app-icon name="building" /></span><div><div class="company-name"><h2>{{organization.name}}</h2>@if(context.allows('organization.manage')){<button class="icon-button" aria-label="Переименовать компанию" title="Переименовать компанию" (click)="name=organization.name;renaming.set(true)"><app-icon name="edit" /></button>}</div><p>Ваше рабочее пространство</p></div><span class="badge">{{label(organization.role)}}</span></div><div class="company-facts"><div><span>Участник</span><strong>{{context.user()?.displayName}}</strong></div><div><span>Email</span><strong>{{context.user()?.email}}</strong></div><div><span>Идентификатор</span><strong>{{organization.id}}</strong></div></div></section>
      @if(renaming()){<form class="panel panel-body" (ngSubmit)="rename()"><label class="field">Название компании<input name="rename" [(ngModel)]="name" required maxlength="80"></label><div class="page-actions"><button type="button" class="btn" (click)="cancelEdit()">Отмена</button><button type="submit" class="btn primary" [disabled]="saving()">Сохранить</button></div></form>}
      <div class="company-links">@for(link of links;track link.route){<a class="panel" [routerLink]="link.route"><app-icon [name]="link.icon" /><div><h3>{{link.label}}</h3><p>{{link.description}}</p></div><app-icon name="chevron" /></a>}</div>
    } @else {<div class="panel empty"><h2>Выберите компанию</h2><a class="btn primary" routerLink="/start">Рабочие пространства</a></div>}
  }
`,styles:`.company-card{display:flex;align-items:center;gap:20px;padding:26px}.company-card>div{flex:1;min-width:0}.company-card p{font-size:12px;color:var(--muted);margin-top:5px}.company-symbol{display:grid;place-items:center;width:55px;height:55px;flex:none;border:1px solid #dee8f8;background:#f0f5fd;color:#4877bb;border-radius:14px}.company-symbol app-icon{width:28px;height:28px}.company-name{display:flex;align-items:center;gap:10px}.company-name h2{font-size:22px;overflow-wrap:anywhere}.company-facts{display:grid;grid-template-columns:1fr 1.15fr 1fr;gap:24px;padding:18px 26px 22px;border-top:1px solid var(--line)}.company-facts span,.company-facts strong{display:block;font-size:12px}.company-facts span{font-size:11px;color:var(--muted);margin-bottom:7px}.company-links{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:20px}.company-links>a{display:flex;align-items:center;gap:13px;padding:20px;min-height:90px;color:#536078}.company-links>a>div{flex:1}.company-links p{font-size:12px;color:var(--muted);margin-top:5px}.company-links app-icon:last-child{width:14px}.profile-heading{display:flex;align-items:center;gap:20px;margin-bottom:24px}@media(max-width:1100px){.company-links{grid-template-columns:1fr}}@media(max-width:540px){.company-card{padding:19px 18px;gap:13px;flex-wrap:wrap}.company-card .btn{margin-left:65px}.company-facts{grid-template-columns:1fr;padding:18px;gap:16px}.company-name h2{font-size:18px}.company-links>a{padding:16px}}`,})
export class OrganizationComponent {
  readonly context=inject(ContextService);private readonly api=inject(ApiService);private readonly session=inject(SessionService);private readonly unsaved=inject(UnsavedChangesService);private readonly router=inject(Router);private readonly routeData=toSignal(inject(ActivatedRoute).data);
  readonly mode=computed(()=>this.routeData()?.['mode']??'organization');readonly error=signal('');readonly saving=signal(false);readonly creating=signal(false);readonly renaming=signal(false);readonly label=stateLabel;name='';invitationToken='';readonly initials=computed(()=>this.context.user()?.displayName.split(/\s+/).slice(0,2).map(value=>value[0]).join('')??'');
  readonly links=[{route:'/accounts',label:'Кабинеты',description:'Кабинеты и подключения',icon:'store'},{route:'/team',label:'Команда и доступ',description:'Участники, роли и приглашения',icon:'users'},{route:'/audit',label:'Аудит компании',description:'История административных изменений',icon:'history'}];
  constructor(){inject(DestroyRef).onDestroy(this.unsaved.register(()=>this.hasUnsavedChanges(),()=>{this.creating.set(false);this.renaming.set(false);this.name='';this.invitationToken='';}));}
  hasUnsavedChanges():boolean{return (this.creating()&&this.name.trim().length>0)||(this.renaming()&&this.name!==this.context.organization()?.name)||this.invitationToken.trim().length>0;}
  @HostListener('window:beforeunload',['$event']) beforeUnload(event:BeforeUnloadEvent):void{if(this.hasUnsavedChanges())event.preventDefault();}
  async cancelEdit():Promise<void>{if(await this.unsaved.confirm()){this.creating.set(false);this.renaming.set(false);this.name='';}}
  async select(organization:Organization):Promise<void>{this.saving.set(true);this.error.set('');try{if(await this.session.selectOrganization(organization))await this.router.navigateByUrl('/organization');}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.saving.set(false);}}
  async create():Promise<void>{if(this.saving())return;this.saving.set(true);try{const organization=await this.api.createOrganization({body:{...mutation(),name:this.name.trim()}});this.creating.set(false);await this.session.selectOrganization(organization);await this.router.navigateByUrl('/organization');}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.saving.set(false);}}
  async rename():Promise<void>{const organization=this.context.organization();if(!organization||this.saving())return;this.saving.set(true);try{const result=await this.api.updateOrganization({path:{id:organization.id},body:{...mutation(organization.revision),name:this.name.trim()}});this.context.organization.set(result);this.context.user.update(user=>user?{...user,organizations:user.organizations.map(value=>value.id===result.id?{...value,...result}:value)}:null);this.renaming.set(false);}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.saving.set(false);}}
  async acceptInvitation():Promise<void>{if(this.saving())return;this.saving.set(true);try{await this.api.acceptInvitation({body:{clientRequestId:crypto.randomUUID(),token:this.invitationToken}});this.invitationToken='';const user=await this.api.getMe();this.context.user.set(user);await this.router.navigateByUrl('/start');}catch(error:unknown){this.error.set(errorMessage(error));}finally{this.saving.set(false);}}
}
