import { FilterField, GridColumn, ScreenDefinition } from '../core/models';
import { stateLabel } from '../core/api.service';

const column=(id:string,label:string,width=160,group?:string,hidden=false):GridColumn=>({id,label,width,group,hidden});
const eventColumns=[column('date','Дата',180),column('name','Событие',290),column('amount','Сумма'),column('status','Состояние',190),column('source','Источник',200)];
export const screens:Record<string,ScreenDefinition>={
  products:{key:'products',title:'Товары',section:'Операции',scope:'account',resource:'offers',columns:[column('product','Товар',280,'Товар'),column('price','Цена',130,'Цены'),column('buyer','Наблюдаемая цена',170,'Цены'),column('cost','Себестоимость',160,'Себестоимость'),column('costFrom','Действует с',152,'Себестоимость'),column('costTo','Действует до',152,'Себестоимость'),column('policy','Политика',180,'Автоматизация'),column('mode','Режим назначения',180,'Автоматизация',true),column('assignmentStatus','Состояние назначения',195,'Автоматизация',true),column('runAt','Последний прогон',170,'Автоматизация'),column('decision','Результат прогона',186,'Автоматизация'),column('command','Последняя команда',184,'Автоматизация'),column('commandState','Состояние команды',196,'Автоматизация'),column('promo','Промо',180,'Цены'),column('commission','Комиссия',145,'Экономика'),column('margin','Маржа',135,'Экономика'),column('priceIndex','Индекс цены',140,'Цены'),column('stock','Доступный остаток',148,'Запасы',true)]},
  automation:{key:'automation',title:'Автоматизация',section:'Операции',scope:'organization',resource:'policies',columns:[column('name','Политика',330),column('status','Состояние',155),column('version','Версия',135),column('assignments','Назначения',170),column('scopes','Области',180),column('strategy','Способ выбора цены',240,undefined,true)]},
  finance:{key:'finance',title:'Начисления',section:'Аналитика',scope:'account',resource:'economics/accruals',columns:[column('date','Учётная дата',155),column('name','Компонент',240),column('income','Доход'),column('cost','Себестоимость'),column('expenses','Расходы'),column('tax','Налог'),column('profit','Результат'),column('status','Основание / полнота',205)]},
  payments:{key:'payments',title:'Выплаты',section:'Аналитика',scope:'account',resource:'economics/payments',columns:[column('date','Дата выплаты',185),column('name','Внешний идентификатор',240),column('amount','Сумма',170),column('scope','Область',170),column('source','Основание',240)]},
  expenses:{key:'expenses',title:'Расходы и налог',section:'Аналитика',scope:'account',resource:'seller-costs/revisions',columns:[column('name','Товар',250),column('amount','Собственные расходы / единица',235),column('cost','Себестоимость / единица',210),column('date','Действует с',155),column('until','Действует до',155),column('revision','Редакция',125),column('source','Автор',220)]},
  units:{key:'units',title:'Экономика товаров',section:'Аналитика',scope:'account',resource:'economics/calculations',columns:[column('product','Товар',280),column('price','Цена расчёта'),column('cost','Себестоимость'),column('profit','Прибыль расчёта'),column('status','Состояние',190),column('freshness','Актуальность',220),column('date','Рассчитано',190)]},
  inventory:{key:'inventory',title:'Запасы',section:'Аналитика',scope:'account',resource:'stock-pools',columns:[column('product','Товар',280),column('warehouse','Склад',210),column('physical','Физический остаток'),column('available','Доступно'),column('reserved','В резерве площадки'),column('observed','Получено',180)]},
  returns:{key:'returns',title:'Возвраты',section:'Аналитика',scope:'account',resource:'economics/returns',columns:[column('date','Дата возврата',185),column('name','Строка заказа',240),column('quantity','Количество',155),column('amount','Возвращено денег',185),column('refund','Возврат денег',180),column('receipt','Физическая приёмка',190),column('resalable','Пригодность',160),column('stock','Наличие в запасе',180)]},
  outlook:{key:'outlook',title:'Ориентир при текущих условиях',section:'Аналитика',scope:'account',resource:'economics/sales-pace',columns:[column('product','Товар',280),column('rate','Наблюдаемый темп',200),column('period','Период',200),column('quantity','Количество',160),column('source','Основание',240),column('status','Состояние',190)]},
  competitors:{key:'competitors',title:'Конкуренты',section:'Конкуренты',scope:'account',resource:'competitor-observations',columns:[column('product','Наш товар',280),column('seller','Продавец',200),column('price','Цена комплекта',160),column('delivery','Доставка',150),column('status','Состояние записи',190),column('date','Наблюдалось',190)]},
  team:{key:'team',title:'Команда и доступ',section:'Компания',scope:'organization',resource:'memberships',columns:[column('name','Участник',250),column('email','Email',270),column('role','Роль',170),column('status','Состояние',170)]},
  invitations:{key:'invitations',title:'Приглашения',section:'Компания',scope:'organization',resource:'invitations',columns:[column('email','Email',270),column('role','Роль',170),column('expires','Действует до',190),column('status','Состояние',170),column('mail','Доставка письма',190)]},
  'account-team':{key:'account-team',title:'Доступ к кабинету',section:'Доступ к кабинету',scope:'account',resource:'account-access',columns:[column('name','Участник',250),column('email','Email',270),column('role','Роль',170),column('status','Состояние',170)]},
  audit:{key:'audit',title:'Аудит компании',section:'Компания',scope:'organization',resource:'audit',columns:[column('date','Дата',190),column('actor','Участник',220),column('action','Действие',240),column('resource','Объект',230),column('details','Подробности',300)]},
  'account-audit':{key:'account-audit',title:'Аудит кабинета',section:'Аудит кабинета',scope:'account',resource:'audit',columns:[column('date','Дата',190),column('actor','Участник',220),column('action','Действие',240),column('resource','Объект',230),column('details','Подробности',300)]},
  tasks:{key:'tasks',title:'Фоновые задачи',section:'События',scope:'account',resource:'operations',columns:[column('name','Задача',290),column('date','Создана',190),column('status','Состояние',210),column('progress','Прогресс',170)]},
  imports:{key:'imports',title:'История импорта',section:'Фоновые задачи',scope:'account',resource:'imports',columns:[column('name','Файл',290),column('date','Создан',190),column('status','Состояние',210),column('kind','Тип импорта',170),column('rows','Строк',120),column('errors','Ошибок',120)]},
  reports:{key:'reports',title:'История экспорта',section:'Фоновые задачи',scope:'account',resource:'reports',columns:[column('name','Отчёт',290),column('date','Создан',190),column('status','Состояние',210),column('format','Формат',120),column('dataStatus','Полнота данных',180),column('rows','Строк',130),column('expires','Доступен до',190)]},
};

export const strategyLabels:Record<string,string>={HOLD_PRICE:'Удержание цены',TARGET_PROFITABILITY:'Целевая прибыльность',FOLLOW_COMPETITOR:'Следование конкуренту'};

const status=(values:string[]):FilterField=>({id:'status',label:'Состояние',type:'select',options:values.map(value=>({value,label:stateLabel(value)}))});
const dates=(required=false):FilterField[]=>[{id:'from',label:'Дата с',type:'date',required},{id:'to',label:'Дата по включительно',type:'date',required}];
const offer:FilterField={id:'offerId',label:'Товар',type:'reference',reference:'offers'};
const active=status(['ACTIVE','REVOKED']);
export const screenFilters:Readonly<Record<string,FilterField[]>>={
  products:[{id:'sku',label:'Артикул',type:'text'},{id:'name',label:'Название товара',type:'text'},{id:'priceMin',label:'Цена от, ₽',type:'text'},{id:'priceMax',label:'Цена до, ₽',type:'text'},{id:'buyerMin',label:'Цена покупателя от, ₽',type:'text'},{id:'buyerMax',label:'Цена покупателя до, ₽',type:'text'},{id:'costMin',label:'Себестоимость от, ₽',type:'text'},{id:'costMax',label:'Себестоимость до, ₽',type:'text'},{id:'costFrom',label:'Себестоимость действует с',type:'date'},{id:'costTo',label:'Конец интервала себестоимости',type:'date'},{id:'policy',label:'Политика',type:'text'},{id:'mode',label:'Режим назначения',type:'select',options:['PREVIEW','MANUAL','AUTO'].map(value=>({value,label:stateLabel(value)}))},{id:'assignmentStatus',label:'Состояние назначения',type:'text'},{id:'runFrom',label:'Последний прогон с',type:'date'},{id:'runTo',label:'Последний прогон по',type:'date'},{id:'decisionId',label:'Идентификатор расчёта',type:'text'},{id:'decisionStatus',label:'Состояние расчёта',type:'text'},{id:'commandId',label:'Идентификатор команды',type:'text'},{id:'commandState',label:'Состояние команды',type:'select',options:['PENDING','SENT','APPLIED','PARTIALLY_APPLIED','FAILED','UNKNOWN','CANCELLED'].map(value=>({value,label:stateLabel(value)}))},{id:'commissionMin',label:'Комиссия от, доля',type:'text'},{id:'commissionMax',label:'Комиссия до, доля',type:'text'},{id:'marginMin',label:'Маржа от, доля',type:'text'},{id:'marginMax',label:'Маржа до, доля',type:'text'},{id:'promo',label:'Участие в акции',type:'text'},{id:'priceIndexMin',label:'Индекс цены от',type:'text'},{id:'priceIndexMax',label:'Индекс цены до',type:'text'},{id:'stockMin',label:'Остаток от',type:'text'},{id:'stockMax',label:'Остаток до',type:'text'}],automation:[status(['DRAFT','ACTIVE','PAUSED','ARCHIVED']),{id:'scopes',label:'Область назначения',type:'select',options:[{value:'ACCOUNT',label:'Кабинет'},{value:'CATEGORY',label:'Категория'},{value:'OFFER',label:'Товар'}]},{id:'hasAssignments',label:'Назначения',type:'select',options:[{value:'YES',label:'Есть назначения'},{value:'NO',label:'Без назначений'}]},{id:'version',label:'Версия',type:'text'},{id:'strategy',label:'Способ выбора цены',type:'select',options:[{value:'HOLD_PRICE',label:'Удерживать цену'},{value:'TARGET_PROFITABILITY',label:'Целевая прибыльность'},{value:'FOLLOW_COMPETITOR',label:'Следовать конкуренту'}]}],
  finance:[...dates(true),status(['CONFIRMED','PRELIMINARY','INCOMPLETE','UNKNOWN']),offer,{id:'component',label:'Компонент начисления',type:'text'}],
  payments:dates(true),returns:dates(true),expenses:[...dates(),offer],
  units:[...dates(),offer,status(['CALCULATED','INCOMPLETE','BLOCKED','NO_CHANGE','NOT_CALCULATED'])],
  inventory:[offer,{id:'warehouseId',label:'Склад',type:'reference',reference:'warehouses'},{id:'warehouse',label:'Название склада',type:'text'},{id:'physicalMin',label:'Физический остаток от',type:'text'},{id:'physicalMax',label:'Физический остаток до',type:'text'},{id:'availableMin',label:'Доступно от',type:'text'},{id:'availableMax',label:'Доступно до',type:'text'},{id:'reservedMin',label:'В резерве площадки от',type:'text'},{id:'reservedMax',label:'В резерве площадки до',type:'text'}],outlook:[status(['AVAILABLE','INCOMPLETE'])],competitors:[offer,{id:'sourceId',label:'Источник наблюдения',type:'reference',reference:'competitor-sources'},{id:'segment',label:'Сопоставимые условия',type:'text'},status(['ACTIVE','REVOKED'])],
  team:[active],'account-team':[active],invitations:[status(['PENDING','ACCEPTED','REVOKED','EXPIRED'])],
  audit:dates(),'account-audit':dates(),
  tasks:[...dates(),status(['READY','RUNNING','WAITING','SUCCEEDED','BLOCKED','DEAD','CANCELLED'])],
  imports:[...dates(),status(['DRAFT','PREPARING','VALIDATED','INVALID','COMMITTED','STALE','FAILED','CANCELLED']),{id:'kind',label:'Тип импорта',type:'select',options:[{value:'COSTS',label:'Себестоимость'},{value:'SELLER_COSTS',label:'Расходы продавца'},{value:'TAX',label:'Налог'},{value:'PRICE_PARAMETERS',label:'Параметры цен'},{value:'COMPETITORS',label:'Конкуренты'}]}],
  reports:[...dates(),status(['PENDING','PREPARING','READY','FAILED','EXPIRED'])],
};
