import { Temporal } from '@js-temporal/polyfill';
import { ViewRefresh } from '../core/view-refresh';
import { PriceIndexDialogComponent } from '../shared/price-index-dialog.component';
import { AssignmentBatchDialogComponent } from '../shared/assignment-batch-dialog.component';
import { TaxDialogComponent } from '../shared/economics-dialogs';
import { AccessDialogComponent, BulkAssignmentDialogComponent, ImportReviewDialogComponent, InvitationDialogComponent, ExportDialogComponent } from '../shared/workflow-dialogs';
import { Component, DestroyRef, effect, inject, signal, untracked } from '@angular/core';
import { ActivatedRoute, Router, RouterLink, RouterLinkActive } from '@angular/router';
import { toSignal } from '@angular/core/rxjs-interop';
import { MatDialog } from '@angular/material/dialog';
import { firstValueFrom } from 'rxjs';
import { ApiService, dateTime, decimal, percentage, errorMessage, operationMessage, mutation, stateLabel } from '../core/api.service';
import { ContextService } from '../core/context.service';
import { FeedbackService } from '../core/feedback.service';
import { RealtimeService } from '../core/realtime.service';
import { ViewStateService, initialView } from '../core/view-state.service';
import { AccountAccess, AuditRecord, BackgroundOperation, CompetitorObservation, CostRevision, EconomicsCalculation, FinanceRecord, GridCell, GridRow, ImportSummary, Invitation, Membership, Offer, Page, Payment, Policy, ReportSummary, ReturnRecord, SalesPace, Stock, ViewState } from '../core/models';
import { GridComponent } from '../shared/grid.component';
import { IconComponent } from '../shared/icon.component';
import { CompetitorDialogComponent, ConfirmDialogComponent, DetailDialogComponent, FilterDialogComponent, ImportDialogComponent, InviteDialogComponent, PolicyDialogComponent } from '../shared/dialogs';
import { RequestScope } from '../api/angular-client.gen';
import { screens, screenFilters, strategyLabels } from './screens';

@Component({selector:'app-workspace',imports:[GridComponent,IconComponent,RouterLink,RouterLinkActive],template:`
  <h1 class="sr-only">{{screen().title}}</h1>
  @if (screen().section==='Операции') { <div class="page-navigation"><nav class="tabs"><a routerLink="/products" routerLinkActive="active">Товары</a><a routerLink="/automation" routerLinkActive="active">Автоматизация</a></nav><div class="page-actions">@if(screen().key==='automation'&&context.allows('organization.policy.manage')){<button class="btn primary" (click)="createPolicy()"><app-icon name="plus" />Создать политику</button>}@if(screen().key==='products'&&context.allows('finance.write')){<button class="btn" (click)="importData()"><app-icon name="upload" />Импорт</button>}</div></div> }
  @if (screen().section==='Аналитика') { <nav class="tabs"><a routerLink="/analytics" routerLinkActive="active">Обзор</a><a routerLink="/finance" [class.active]="['finance','payments','expenses'].includes(screen().key)">Финансы</a><a routerLink="/units" [class.active]="['units','inventory','returns'].includes(screen().key)">Товары и запасы</a><a routerLink="/outlook" routerLinkActive="active">Ориентир при текущих условиях</a></nav>@if(['finance','payments','expenses'].includes(screen().key)){<nav class="tabs compact"><a routerLink="/finance" routerLinkActive="active">Начисления</a><a routerLink="/payments" routerLinkActive="active">Выплаты</a><a routerLink="/expenses" routerLinkActive="active">Расходы и налог</a></nav>}@if(['units','inventory','returns'].includes(screen().key)){<nav class="tabs compact"><a routerLink="/units" routerLinkActive="active">Экономика товаров</a><a routerLink="/inventory" routerLinkActive="active">Запасы</a><a routerLink="/returns" routerLinkActive="active">Возвраты</a></nav>} }
  @if(screen().key==='expenses'&&context.allows('finance.write')){<div class="page-actions"><button class="btn" (click)="editTax()">Налоговый профиль</button><a class="btn" routerLink="/products">Стоимость и расходы товара</a><button class="btn" (click)="importData()"><app-icon name="upload" />Импорт расходов</button></div>}
  @if(screen().key==='competitors'&&context.allows('competitor.write')){<div class="page-actions"><button class="btn" (click)="importData()"><app-icon name="upload" />Импорт</button><button class="btn primary" (click)="addCompetitor()"><app-icon name="plus" />Добавить наблюдение</button></div>}
  @if(['team','invitations'].includes(screen().key)){<nav class="tabs"><a routerLink="/team" routerLinkActive="active">Участники</a><a routerLink="/invitations" routerLinkActive="active">Приглашения</a></nav>}
  @if(screen().key==='account-team'&&context.allows('membership.manage')){<div class="page-actions"><button class="btn primary" (click)="grantAccess()"><app-icon name="plus" />Выдать доступ</button></div>}@if(['team','invitations'].includes(screen().key)&&context.allows('membership.manage')){<div class="page-actions"><button class="btn primary" (click)="invite()"><app-icon name="plus" />Пригласить участника</button></div>}
  @if(['tasks','imports','reports'].includes(screen().key)){<nav class="tabs"><a routerLink="/tasks" routerLinkActive="active">Фоновые задачи</a><a routerLink="/imports" routerLinkActive="active">История импорта</a><a routerLink="/reports" routerLinkActive="active">История экспорта</a></nav>}
  @if(screen().key==='automation'){<div class="context-line"><app-icon name="building" /><span>Политики компании <strong>{{context.organization()?.name}}</strong></span><span class="spacer"></span><span>Назначения: {{context.account()?.name || 'Кабинет не выбран'}}</span></div>}
  @if(['reports','tasks'].includes(screen().key)){<div class="page-actions"><button class="btn" [class.primary]="organizationHistory()" (click)="setHistoryScope(true)">{{screen().key==='tasks'?'Задачи компании':'Экспорт компании'}}</button><button class="btn" [class.primary]="!organizationHistory()" [disabled]="!context.account()" (click)="setHistoryScope(false)">{{screen().key==='tasks'?'Задачи кабинета':'Экспорт кабинета'}}</button></div>}
  @if(screen().key==='outlook'&&context.allows('decision.preview')){<div class="page-actions"><button class="btn" [disabled]="refreshingPace()" (click)="refreshPace()">Рассчитать ориентир</button></div>}
  @if(screen().key==='outlook'){<div class="notice"><app-icon name="info" /><span>Наблюдаемый темп описывает историю. Ориентир действует при сохранении текущих условий и не обещает будущую прибыль.</span></div>}
  @if(accountScoped()&&!context.account()){<section class="panel empty"><app-icon name="store" /><h2>Выберите кабинет</h2><p>Коммерческие данные всегда относятся к одному кабинету.</p><a class="btn primary" routerLink="/accounts">К кабинетам</a></section>}
  @else if(error()){<div class="notice error" role="alert"><app-icon name="alert" /><span>{{error()}}</span><button class="btn" (click)="reload()">Повторить</button></div>}
  @if(viewReady()){
    @if(viewStore.status()){<p class="view-status" role="status">{{viewStore.status()}}@if(viewStore.conflict()){<button class="link" (click)="viewStore.resolveConflict()">Применить мой вид</button>}@else{<button class="link" (click)="viewStore.retry()">Повторить сохранение</button>}</p>}
    <app-grid [error]="error()" [exportAllowed]="context.allows('export')" [title]="screen().title" [columns]="visibleColumns()" [rows]="rows()" [total]="total()" [view]="view()" [loading]="loading()" [selectable]="screen().key==='products'" [selected]="selected()" (selectionChanged)="selected.set($event)" (viewChanged)="viewChanged($event)" (openRow)="openRow($event)" (cellAction)="cellAction($event)" (filters)="filters()" (exportRequested)="export()" (resetRequested)="resetView()" (fullResetRequested)="fullResetView()"><div selectionActions>@if(context.allows('policy.assign')&&context.allows('finance.read')){<button class="btn primary" [disabled]="!context.allows('organization.policy.read')" [title]="context.allows('organization.policy.read')?'Назначить политику':'Для выбора требуется право чтения каталога политик компании'" (click)="bulkAssign()">Назначить политику</button>}</div></app-grid>
  }
`})
export class WorkspaceComponent {
  readonly organizationHistory=signal(false);readonly refreshingPace=signal(false);
  readonly context=inject(ContextService);readonly viewStore=inject(ViewStateService);
  private readonly api=inject(ApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);
  private readonly dialog=inject(MatDialog);private readonly realtime=inject(RealtimeService);private readonly feedback=inject(FeedbackService);
  private readonly routeData=toSignal(this.route.data);
  readonly screen=signal(screens['products']);readonly view=signal<ViewState>(initialView());readonly viewReady=signal(false);readonly rows=signal<GridRow[]>([]);readonly total=signal(0);readonly loading=signal(false);readonly error=signal('');readonly selected=signal<string[]>([]);
  private records=new Map<string,Payment|ReturnRecord|SalesPace|CostRevision|ReportSummary|ImportSummary|Invitation|AccountAccess|Offer|Policy|CompetitorObservation|Membership|BackgroundOperation|FinanceRecord|EconomicsCalculation|Stock|AuditRecord>();
  private unsubscribe?:()=>void;private assignmentUnsubscribe?:()=>void;private epoch=0;private wanted=0;private readonly reads=new ViewRefresh(inject(DestroyRef));private searchTimer?:ReturnType<typeof setTimeout>;
  constructor(){
    effect(()=>{const key=this.routeData()?.['screen'];this.context.identity();this.context.permissions();if(typeof key==='string'&&screens[key]){this.screen.set(screens[key]);untracked(()=>void this.activate());}});
    inject(DestroyRef).onDestroy(()=>{this.epoch++;this.unsubscribe?.();this.assignmentUnsubscribe?.();clearTimeout(this.searchTimer);});
  }
  private async activate():Promise<void>{const epoch=++this.epoch;this.unsubscribe?.();this.assignmentUnsubscribe?.();this.viewReady.set(false);this.rows.set([]);this.selected.set([]);this.total.set(0);this.error.set('');if(!this.context.organization()||(this.accountScoped()&&!this.context.account()))return;try{const state=await this.viewStore.open(this.screen().key,this.accountScoped());if(epoch!==this.epoch)return;this.view.set(this.applyDateDrilldown(state));this.viewReady.set(true);this.loading.set(true);this.unsubscribe=this.realtime.subscribe([this.screen().resource],async()=>{await this.reload();return !this.error();},!this.accountScoped(),{owner:this.reads,key:'grid'});if(this.screen().key==='automation'&&this.context.account()&&this.context.allows('policy.read'))this.assignmentUnsubscribe=this.realtime.subscribe(['policy-assignments'],async()=>{await this.reload();return !this.error();},false,{owner:this.reads,key:'grid'});}catch(error:unknown){if(epoch===this.epoch){this.error.set(errorMessage(error));this.loading.set(false);}}}
  private applyDateDrilldown(state:ViewState):ViewState {
    if(this.screen().key!=='finance')return state;
    const params=this.route.snapshot.queryParamMap;
    const monthValue=params.get('month'),fromValue=params.get('from'),toValue=params.get('to');
    if(monthValue===null&&fromValue===null&&toValue===null)return state;
    void this.router.navigate([],{relativeTo:this.route,queryParams:{month:null,from:null,to:null},queryParamsHandling:'merge',replaceUrl:true});
    try {
      let from:Temporal.PlainDate,to:Temporal.PlainDate;
      if(monthValue!==null){
        if(fromValue!==null||toValue!==null||!(/^[1-9][0-9]{3}-(0[1-9]|1[0-2])$/).test(monthValue))throw new Error('Invalid month');
        const month=Temporal.PlainYearMonth.from(monthValue);
        from=month.toPlainDate({day:1});to=month.toPlainDate({day:month.daysInMonth});
      }else{
        const pattern=/^[1-9][0-9]{3}-[0-9]{2}-[0-9]{2}$/;
        if(!fromValue||!toValue||!pattern.test(fromValue)||!pattern.test(toValue))throw new Error('Invalid dates');
        from=Temporal.PlainDate.from(fromValue);to=Temporal.PlainDate.from(toValue);
        const days=from.until(to).days;if(days<0||days>=366)throw new Error('Invalid period');
      }
      const next={...state,query:{...state.query,search:'',filters:{from:from.toString(),to:to.toString()},page:0}};
      this.viewStore.save(next);return next;
    }catch{
      this.feedback.show('Некорректный период в ссылке. Сохранённые фильтры не изменены.',true);return state;
    }
  }
  reload():Promise<void>{if(!this.viewReady())return this.activate();this.wanted++;return this.reads.run('grid',()=>this.load(),()=>!this.error());}
  private async load():Promise<void>{this.loading.set(true);const epoch=this.epoch,wanted=this.wanted;const screen=this.screen();try{const records:typeof this.records=new Map();const page=await this.fetchRows(screen.key,records);if(epoch!==this.epoch||wanted!==this.wanted)return;this.records=records;this.rows.set(page.items);this.total.set(page.total);this.error.set('');}catch(error:unknown){if(epoch===this.epoch)this.error.set(errorMessage(error));}finally{if(epoch===this.epoch)this.loading.set(false);}}
  private async mapPage<T extends {id:string}>(request:Promise<Page<T>>,mapper:(value:T)=>GridRow):Promise<Page<GridRow>>{const page=await request;return{...page,items:page.items.map(mapper)};}
  accountScoped():boolean{return this.screen().scope==='account'&&!(['reports','tasks'].includes(this.screen().key)&&(this.organizationHistory()||!this.context.account()));}
  private requestScope():RequestScope{return{organizationId:this.context.organization()?.id??'',accountId:(this.accountScoped()||this.screen().key==='automation')?this.context.account()?.id:undefined};}
  setHistoryScope(organization:boolean):void{this.organizationHistory.set(organization);void this.activate();}
  async refreshPace():Promise<void>{if(this.refreshingPace())return;this.refreshingPace.set(true);try{await this.api.refreshSalesPace({body:{clientRequestId:crypto.randomUUID()}});this.feedback.show('Расчёт принят. Результаты обновятся после фоновой обработки.');}catch(error:unknown){this.feedback.show(errorMessage(error),true);}finally{this.refreshingPace.set(false);}}
  private gridQuery(){const {filters,sort,...query}=this.view().query;const [field,order]=sort.split(',');const direction:'asc'|'desc'=order==='desc'?'desc':'asc';const names:Readonly<Record<string,string>>=this.screen().key==='products'?{product:'name',price:'sellerPrice',buyer:'buyerPrice'}:this.screen().key==='competitors'?{date:'observedAt',id:'observedAt'}:['audit','account-audit'].includes(this.screen().key)?{actor:'actorId',resource:'targetId'}:{};return {...query,...filters,sort:names[field]??field,direction};}
  private date(value:string|undefined):string{return dateTime(value,this.context.account()?.timezone??'UTC');}
  private proof(value:boolean|undefined):string{return value===undefined?'Нет данных':value?'Подтверждено':'Не подтверждено';}
  private cell(text:string,kind:GridCell['kind']='text',detail?:string):GridCell{return{text,kind,detail};}
  private status(value:string|undefined):GridCell{return{text:stateLabel(value),kind:'status',tone:['CONFIRMED','COMPLETED','PUBLISHED','ACTIVE','READY'].includes(value??'')?'success':['FAILED','UNKNOWN','REVOKED'].includes(value??'')?'warning':''};}
  private async fetchRows(key:string,records:typeof this.records):Promise<Page<GridRow>>{
    if(key==='products')return this.mapPage<Offer>(this.api.listOffers({query:this.gridQuery()},this.requestScope()),offer=>{records.set(offer.id,offer);return{id:offer.id,revision:offer.revision,cells:{product:{text:offer.name,detail:offer.sku,kind:'product',imageUrl:offer.imageUrl},price:this.cell(decimal(offer.sellerPrice),'money'),buyer:this.cell(decimal(offer.buyerPrice),'money'),cost:this.cell(decimal(offer.cost),'money'),costFrom:this.cell(offer.costFrom??'Не задано'),costTo:this.cell(offer.cost===undefined?'Нет данных':offer.costTo??'Бессрочно'),policy:this.cell(offer.policyName??'Не назначена'),mode:this.status(offer.mode),assignmentStatus:this.status(offer.assignmentStatus),runAt:this.cell(this.date(offer.lastCalculationAt)),decision:{...this.cell(offer.lastDecisionId?stateLabel(offer.decisionStatus):'Нет расчёта','text',offer.lastDecisionId),action:!!offer.lastDecisionId},command:{...this.cell(offer.lastCommandId??'Не создавалась'),action:!!offer.lastCommandId},commandState:this.status(offer.commandState),promo:this.cell(offer.promotions===undefined?'Нет данных':offer.promotions.map(promo=>promo.name).join(', ')||'Не участвует'),priceIndex:{...this.cell(decimal(offer.priceIndex,'')),action:true},commission:this.cell(percentage(offer.commission)),margin:this.cell(percentage(offer.margin)),stock:this.cell(offer.stock??'Нет данных')}};});
    if(key==='automation')return this.mapPage<Policy>(this.api.listPolicies({query:this.gridQuery()},this.requestScope()),policy=>{records.set(policy.id,policy);return{id:policy.id,cells:{name:this.cell(policy.name),status:this.status(policy.status),version:this.cell(String(policy.version)),assignments:this.cell(policy.assignmentsCount==null?(this.context.account()?'Нет доступа':'Кабинет не выбран'):String(policy.assignmentsCount)),scopes:this.cell(policy.assignmentScopes==null?(this.context.account()?'Нет доступа':'Кабинет не выбран'):policy.assignmentScopes.map(scope=>({ACCOUNT:'Кабинет',CATEGORY:'Категория',OFFER:'Товар'}[scope])).join(' · ')||'Не назначена'),strategy:this.cell(strategyLabels[policy.settings.regularRule.strategy]??policy.settings.regularRule.strategy)}};});
    if(key==='competitors'){const query=this.gridQuery();const allowedSorts=['product','seller','price','delivery','observedAt','status'] as const;const sort=allowedSorts.find(value=>value===query.sort);if(!sort)throw new Error('Неизвестная сортировка наблюдений. Сбросьте расположение таблицы.');return this.mapPage<CompetitorObservation>(this.api.listCompetitors({query:{...query,sort}},this.requestScope()),observation=>{records.set(observation.id,observation);return{id:observation.id,cells:{product:this.cell(observation.offerName,'product',observation.offerId),seller:this.cell(observation.sellerName),price:this.cell(decimal(observation.price),'money'),delivery:this.cell(decimal(observation.delivery),'money'),status:this.status(observation.revoked?'REVOKED':'ACTIVE'),date:this.cell(this.date(observation.observedAt))}};});}
    if(key==='invitations')return this.mapPage<Invitation>(this.api.listInvitations({query:this.gridQuery()},this.requestScope()),invitation=>{records.set(invitation.id,invitation);return{id:invitation.id,cells:{email:this.cell(invitation.email),role:this.cell(stateLabel(invitation.role)),expires:this.cell(this.date(invitation.expiresAt)),status:this.status(invitation.consumedAt?'ACCEPTED':invitation.revokedAt?'REVOKED':Date.parse(invitation.expiresAt)<=Date.now()?'EXPIRED':'PENDING'),mail:this.status(invitation.mailState)}};});
    if(['team','account-team'].includes(key))return this.mapPage<Membership|AccountAccess>(key==='team'?this.api.listMemberships({query:this.gridQuery()},this.requestScope()):this.api.listAccountAccess({query:this.gridQuery()},this.requestScope()),member=>{records.set(member.id,member);return{id:member.id,cells:{name:this.cell(member.displayName),email:this.cell(member.email),role:this.cell(stateLabel(member.role)),status:this.status(member.active?'ACTIVE':'REVOKED')}};});
    if(['audit','account-audit'].includes(key))return this.mapPage<AuditRecord>(this.api.listAudit({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{date:this.cell(this.date(record.createdAt)),actor:this.cell(record.actorId??'Система'),action:this.cell(record.action),resource:this.cell(record.targetId??'Весь контекст'),details:this.cell(record.details)}};});
    if(key==='inventory')return this.mapPage<Stock>(this.api.listStocks({query:this.gridQuery()},this.requestScope()),stock=>{records.set(stock.id,stock);return{id:stock.id,cells:{product:this.cell(stock.name,'product',stock.offerId),warehouse:this.cell(stock.warehouse),physical:this.cell(stock.physical??'Нет данных'),available:this.cell(stock.available??'Нет данных'),reserved:this.cell(stock.reserved??'Нет данных'),observed:this.cell(this.date(stock.observedAt))}};});
    if(key==='units')return this.mapPage<EconomicsCalculation>(this.api.listCalculations({query:this.gridQuery()},this.requestScope()),calculation=>{records.set(calculation.id,calculation);return{id:calculation.id,cells:{product:this.cell(calculation.offerName,'product',calculation.offerId),price:this.cell(decimal(calculation.price),'money'),cost:this.cell(decimal(calculation.cost),'money'),profit:this.cell(decimal(calculation.profit),'money'),status:this.status(calculation.status),freshness:this.cell(calculation.decisionId?(calculation.current?'Актуален':'Требуется новый расчёт'):'Нет расчёта'),source:this.cell(calculation.reason),date:this.cell(this.date(calculation.calculatedAt))}};});
    if(key==='imports')return this.mapPage<ImportSummary>(this.api.listImports({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{name:this.cell(record.name),date:this.cell(this.date(record.createdAt)),status:this.status(record.status),kind:this.cell(record.kind),rows:this.cell(String(record.totalRows)),errors:this.cell(String(record.errorRows))}};});
    if(key==='reports')return this.mapPage<ReportSummary>(this.api.listReports({query:this.gridQuery()},this.requestScope()),report=>{records.set(report.id,report);return{id:report.id,cells:{name:this.cell(report.name),date:this.cell(this.date(report.createdAt)),status:this.status(report.status),format:this.cell(report.format),dataStatus:this.cell(report.dataStatus==='COMPLETE'?'Полные':report.dataStatus==='INCOMPLETE'?'Неполные':'Как опубликованы'),rows:this.cell(String(report.rowCount)),expires:this.cell(this.date(report.expiresAt))}};});
    if(key==='tasks')return this.mapPage<BackgroundOperation>(this.api.listOperations({query:this.gridQuery()},this.requestScope()),operation=>{records.set(operation.id,operation);return{id:operation.id,cells:{name:this.cell(operation.name),date:this.cell(this.date(operation.createdAt)),status:this.status(operation.status),progress:this.cell(operation.progress==null?'Без процента':operation.progress+'%')}};});
    if(key==='outlook')return this.mapPage<SalesPace>(this.api.listSalesPace({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{product:this.cell(record.offerName,'product',record.offerId),rate:this.cell(decimal(record.observedRate,' ед. / 24 ч')),period:this.cell(record.period),quantity:this.cell(decimal(record.quantity,' ед.')),source:this.cell(this.paceReason(record.reason)),status:this.status(record.status)}};});
    if(key==='payments')return this.mapPage<Payment>(this.api.listPayments({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{date:this.cell(this.date(record.occurredAt)),name:this.cell(record.externalId),amount:this.cell(decimal(record.amount),'money'),scope:this.cell(record.scope),source:this.cell(record.rawFileId)}};});
    if(key==='returns')return this.mapPage<ReturnRecord>(this.api.listReturns({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{date:this.cell(this.date(record.returnedAt)),name:this.cell(record.lineId,'text',record.offerId),quantity:this.cell(decimal(record.returnedQuantity,' ед.')),amount:this.cell(decimal(record.refundedAmount),'money'),refund:this.cell(this.proof(record.refundConfirmed)),receipt:this.cell(this.proof(record.physicalReceiptConfirmed)),resalable:this.cell(this.proof(record.resalable)),stock:this.cell(this.proof(record.stockConfirmed))}};});
    if(key==='expenses')return this.mapPage<CostRevision>(this.api.listSellerCosts({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{date:this.cell(record.validFrom),until:this.cell(record.validTo??'Бессрочно'),name:this.cell(record.offerId),amount:this.cell(decimal(record.extraExpense),'money'),cost:this.cell(decimal(record.amount),'money'),revision:this.cell(String(record.revision)),source:this.cell(record.actor??'Нет данных')}};});
    return this.mapPage<FinanceRecord>(this.api.listAccruals({query:this.gridQuery()},this.requestScope()),record=>{records.set(record.id,record);return{id:record.id,cells:{date:this.cell(this.date(record.occurredAt)),name:this.cell(record.name),amount:this.cell(decimal(record.amount),'money'),income:this.cell(decimal(record.income),'money'),cost:this.cell(decimal(record.cost),'money'),expenses:this.cell(decimal(record.expenses),'money'),tax:this.cell(decimal(record.tax),'money'),profit:this.cell(decimal(record.profit),'money'),status:{...this.status(record.status),detail:record.certainty==='UNKNOWN'?'Основание требует перерасчёта':(record.certainty==='PRELIMINARY'?'Оценка':'Подтверждённое начисление')+(record.complete?' · входы известны':' · часть денежных входов неизвестна')},source:this.cell(record.source??record.category)}};});
  }
  viewChanged(state:ViewState):void{const queryChanged=JSON.stringify(state.query)!==JSON.stringify(this.view().query);this.view.set(state);this.viewStore.save(state);if(queryChanged){clearTimeout(this.searchTimer);this.searchTimer=setTimeout(()=>{this.selected.set([]);this.reload();},250);}}
  resetView():void{const state=structuredClone(this.view());state.columns={order:[],hidden:[],widths:{}};state.query.sort=initialView(this.screen().key,this.context.account()?.timezone??'UTC').query.sort;state.query.page=0;this.viewChanged(state);}
  async fullResetView():Promise<void>{const confirmed=await firstValueFrom(this.dialog.open(ConfirmDialogComponent,{width:'520px',data:{title:'Сбросить всё представление?',message:'Поиск, фильтры, период и расположение столбцов вернутся к начальным значениям.',action:'Сбросить всё'}}).afterClosed());if(!confirmed)return;const state=await this.viewStore.reset();if(state){this.view.set(state);this.selected.set([]);this.reload();}}
  visibleColumns(){return this.screen().key==='products'?this.screen().columns.filter(column=>this.productFieldAllowed(column.id)):this.screen().columns;}
  private productFieldAllowed(id:string):boolean{if(/^(cost|commission|margin)/.test(id))return this.context.allows('finance.read');if(/^(policy|mode|assignmentStatus)/.test(id))return this.context.allows('policy.read');if(/^(run|decision|command)/.test(id))return this.context.allows('command.read');return true;}
  private filterFields(){const fields=screenFilters[this.screen().key]??[];return this.screen().key==='products'?fields.filter(field=>this.productFieldAllowed(field.id)):fields;}
  async filters():Promise<void>{const result:Record<string,string>|undefined=await firstValueFrom(this.dialog.open(FilterDialogComponent,{width:'700px',data:{filters:this.view().query.filters,fields:this.filterFields(),defaults:initialView(this.screen().key,this.context.account()?.timezone??'UTC').query.filters}}).afterClosed());if(result){const view=structuredClone(this.view());view.query.filters=result;view.query.page=0;this.viewChanged(view);}}
  createPolicy():void{this.dialog.open(PolicyDialogComponent,{width:'800px',maxWidth:'calc(100vw - 24px)',data:{}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});}
  addCompetitor():void{this.dialog.open(CompetitorDialogComponent,{width:'620px',data:{}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});}
  invite():void{this.dialog.open(InviteDialogComponent,{width:'620px'}).afterClosed().subscribe(changed=>{if(changed)this.reload();});}
  importData():void{this.dialog.open(ImportDialogComponent,{width:'620px'}).afterClosed().subscribe(result=>{if(result){this.feedback.show('Файл принят для проверки. Результат доступен в истории импорта.');void this.router.navigateByUrl('/imports');}});}
  export():void{this.dialog.open(ExportDialogComponent,{width:'620px',data:{requestScope:this.requestScope(),resource:this.screen().resource,query:this.view().query,ids:this.selected(),total:this.total()}}).afterClosed().subscribe(created=>{if(created)this.feedback.show('Экспорт принят. Файл появится в истории экспорта после подготовки.');});}
  editTax():void{this.dialog.open(TaxDialogComponent,{width:'620px'}).afterClosed().subscribe(changed=>{if(changed)this.reload();});}
  grantAccess():void{this.dialog.open(AccessDialogComponent,{width:'620px',data:{account:true}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});}
  async bulkAssign():Promise<void>{try{const selection=await this.api.createSelection({body:{...mutation(),resource:'offers',query:this.view().query,ids:this.selected()}});this.dialog.open(BulkAssignmentDialogComponent,{width:'620px',data:{selectionId:selection.id,total:selection.total}}).afterClosed().subscribe(changed=>{if(changed){this.selected.set([]);this.reload();}});}catch(error:unknown){this.feedback.show(errorMessage(error),true);}}
  private paceReason(reason:string):string{const labels:Readonly<Record<string,string>>={SOURCE_CHANGED:'Изменились исходные условия: нужен новый расчёт темпа',STALE_SOURCE:'Истёк срок пригодности источников',SOURCE_COVERAGE_UNKNOWN:'Полнота наблюдений источника не подтверждена'};return labels[reason]??reason;}
  private paceDetails(record:SalesPace):void{
    const inventory=record.currentInventory;
    const reasons:Readonly<Record<string,string>>={MULTIPLE_STOCK_POOLS:'Несколько пулов: общий срок запаса не определён',SHARED_STOCK_POOL:'Общий пул нескольких размещений: запас не относится только к этому темпу',STOCK_UNKNOWN:'Доступный остаток не подтверждён',STOCK_POOL_LIMIT:'Набор пулов превышает предел подтверждённой оценки',STOCK_PLACEMENT_UNKNOWN:'Принадлежность пула размещению не подтверждена',ZERO_PACE:'При нулевом темпе срок запаса не определён',PACE_UNAVAILABLE:'Нет пригодного актуального темпа',AVAILABLE:'По текущему подтверждённому остатку'};
    const inventoryRows:{label:string;value:string}[]=inventory?[
      {label:'Доступность оценена',value:this.date(inventory.assessedAt)},
      {label:'Число общих пулов',value:String(inventory.poolCount)},
      {label:'Запаса при таком темпе примерно на',value:decimal(inventory.stockDurationDays,' суток по 24 часа')},
      {label:'Основание оценки запаса',value:reasons[inventory.reason]??inventory.reason},
      ...inventory.pools.flatMap(pool=>[
        {label:'Общий пул',value:pool.poolId},
        {label:'Доступно после обязательств и удержаний',value:decimal(pool.availableQuantity,' ед.')},
        {label:'Размещений используют пул',value:String(pool.placementCount)},
        {label:'Редакция и время остатка',value:String(pool.revision)+' · '+this.date(pool.observedAt)},
        {label:'Остаток пригоден до',value:this.date(pool.validUntil)}])
    ]:[{label:'Текущий доступный остаток',value:'Не подтверждён'}];
    this.dialog.open(DetailDialogComponent,{width:'720px',data:{title:'Ориентир при текущих условиях',subtitle:record.offerName,rows:[...inventoryRows,{label:'Размещение',value:record.placementId},{label:'Состояние и причина',value:stateLabel(record.status)+' · '+this.paceReason(record.reason)},{label:'Наблюдаемый период',value:record.period},{label:'Полных суток',value:String(record.observedDays)},{label:'Наблюдаемых секунд',value:String(record.observedSeconds)},{label:'Созданных заказанных единиц',value:decimal(record.orderedUnits,' ед.')},{label:'Темп за 24 часа',value:decimal(record.observedRate,' ед.')},{label:'Будущий интервал',value:this.date(record.futureStart)+' — '+this.date(record.futureEnd)},{label:'Ориентир количества',value:decimal(record.quantity,' ед.')},{label:'Время расчёта',value:this.date(record.calculatedAt)},{label:'Действует до',value:this.date(record.validUntil)},{label:'Источники',value:record.sourceIds.join(', ')||'Не подтверждены'}],note:'Ориентир заказанных единиц при сохранении текущих условий. Он не определяет количество оставленных покупок, будущую прибыль или разрешение на отправку цены.'}});
  }
  cellAction(event:{rowId:string;columnId:string}):void{const record=this.records.get(event.rowId);if(this.screen().key!=='products'||!record||!('sku'in record))return;if(event.columnId==='priceIndex')this.dialog.open(PriceIndexDialogComponent,{width:'720px',data:record});else if(event.columnId==='decision'&&'lastDecisionId'in record&&record.lastDecisionId)void this.router.navigate(['/decisions',record.lastDecisionId]);else if(event.columnId==='command'&&'lastCommandId'in record&&record.lastCommandId)void this.router.navigate(['/commands',record.lastCommandId]);}
  openRow(id:string):void{const record=this.records.get(id);if(!record)return;if(this.screen().key==='outlook'&&'observedSeconds'in record){this.paceDetails(record);return;}if(this.screen().key==='tasks'&&'name'in record&&record.name==='ASSIGNMENT_BATCH'){this.dialog.open(AssignmentBatchDialogComponent,{width:'820px',data:{id}});return;}if(this.screen().key==='products'){void this.router.navigate(['/products',id]);return;}if(this.screen().key==='automation'&&'settings'in record){this.dialog.open(PolicyDialogComponent,{width:'800px',data:{policy:record}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});return;}if(['team','account-team'].includes(this.screen().key)&&'userId'in record&&this.context.allows('membership.manage')){this.dialog.open(AccessDialogComponent,{width:'620px',data:{account:this.screen().key==='account-team',member:record}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});return;}if(this.screen().key==='units'&&'decisionId'in record&&record.decisionId){void this.router.navigate(['/decisions',record.decisionId]);return;}if(this.screen().key==='invitations'&&'mailState'in record){this.dialog.open(InvitationDialogComponent,{width:'620px',data:record});return;}if(this.screen().key==='imports'){this.dialog.open(ImportReviewDialogComponent,{width:'800px',data:{id}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});return;}if(this.screen().key==='competitors'&&'sellerName'in record){this.dialog.open(CompetitorDialogComponent,{width:'620px',data:{observation:record}}).afterClosed().subscribe(changed=>{if(changed)this.reload();});return;}const rows=this.rows().find(row=>row.id===id);if(rows)this.dialog.open(DetailDialogComponent,{width:'620px',data:{title:this.screen().title,subtitle:id,rows:this.screen().columns.map(column=>({label:column.label,value:rows.cells[column.id]?.text??'Нет данных'})),downloadUrl:this.screen().key==='reports'&&'status'in record&&record.status==='READY'?'/api/v1/reports/'+encodeURIComponent(id)+'/download?organizationId='+encodeURIComponent(this.context.organization()?.id??'')+(this.requestScope().accountId?'&accountId='+encodeURIComponent(this.requestScope().accountId??''):''):undefined,note:this.screen().key==='tasks'&&'message'in record?operationMessage(record.message):'Показаны данные сохранённой записи.'}});}
}
