// Generated by npm run generate:api from the canonical OpenAPI contract. Do not edit.
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { inject } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import type * as T from './types.gen';
import * as Z from './zod.gen';

export interface RequestScope {organizationId:string;accountId?:string;}
function contextHeaders(scope:RequestScope|undefined,organizationOnly:boolean):HttpHeaders {
  let headers=new HttpHeaders();
  if(scope){headers=headers.set('X-Organization-Id',scope.organizationId);headers=headers.set('X-Account-Id',scope.accountId??'');}
  if(!scope&&organizationOnly)headers=headers.set('X-Account-Id','');
  return headers;
}

function queryParameters(query?: Record<string,string|number|boolean|undefined>): HttpParams {
  let params = new HttpParams();
  for (const [name,value] of Object.entries(query ?? {})) {
    if (value !== undefined) params = params.set(name,value);
  }
  return params;
}

export abstract class GeneratedApiClient {
  private readonly http = inject(HttpClient);
  async getMe(params: Omit<T.GetMeData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.GetMeResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/me`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetMeResponse.parse(response);
  }

  async getCsrf(params: Omit<T.GetCsrfData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.GetCsrfResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/auth/csrf`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetCsrfResponse.parse(response);
  }

  async createOrganization(params: Omit<T.CreateOrganizationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateOrganizationResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/organizations`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateOrganizationResponse.parse(response);
  }

  async updateOrganization(params: Omit<T.UpdateOrganizationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.UpdateOrganizationResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/organizations/${encodeURIComponent(params.path.id)}`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zUpdateOrganizationResponse.parse(response);
  }

  async transferOwner(params: Omit<T.TransferOwnerData, 'headers'|'url'>, scope?: RequestScope): Promise<T.TransferOwnerResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/organizations/${encodeURIComponent(params.path.id)}/transfer-owner`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zTransferOwnerResponse.parse(response);
  }

  async listAccounts(params: Omit<T.ListAccountsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAccountsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/marketplace-accounts`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAccountsResponse.parse(response);
  }

  async createAccount(params: Omit<T.CreateAccountData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateAccountResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateAccountResponse.parse(response);
  }

  async saveConnection(params: Omit<T.SaveConnectionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SaveConnectionResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/connections`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSaveConnectionResponse.parse(response);
  }

  async getConnection(params: Omit<T.GetConnectionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetConnectionResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/connections`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetConnectionResponse.parse(response);
  }

  async listSources(params: Omit<T.ListSourcesData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListSourcesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/sources`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListSourcesResponse.parse(response);
  }

  async checkConnection(params: Omit<T.CheckConnectionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CheckConnectionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/connections/check`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCheckConnectionResponse.parse(response);
  }

  async syncAccount(params: Omit<T.SyncAccountData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SyncAccountResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/sync`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSyncAccountResponse.parse(response);
  }

  async listOffers(params: Omit<T.ListOffersData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListOffersResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/offers`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListOffersResponse.parse(response);
  }

  async listPolicies(params: Omit<T.ListPoliciesData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListPoliciesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policies`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListPoliciesResponse.parse(response);
  }

  async createPolicy(params: Omit<T.CreatePolicyData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreatePolicyResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policies`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreatePolicyResponse.parse(response);
  }

  async listAssignments(params: Omit<T.ListAssignmentsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAssignmentsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policy-assignments`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAssignmentsResponse.parse(response);
  }

  async createAssignment(params: Omit<T.CreateAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateAssignmentResponse.parse(response);
  }

  async listCostRevisions(params: Omit<T.ListCostRevisionsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListCostRevisionsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/cost-revisions`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCostRevisionsResponse.parse(response);
  }

  async createCostRevision(params: Omit<T.CreateCostRevisionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateCostRevisionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/cost-revisions`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateCostRevisionResponse.parse(response);
  }

  async listAccruals(params: Omit<T.ListAccrualsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAccrualsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/accruals`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAccrualsResponse.parse(response);
  }

  async listPayments(params: Omit<T.ListPaymentsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListPaymentsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/payments`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListPaymentsResponse.parse(response);
  }

  async listSellerCosts(params: Omit<T.ListSellerCostsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListSellerCostsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/seller-costs/revisions`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListSellerCostsResponse.parse(response);
  }

  async createSellerCost(params: Omit<T.CreateSellerCostData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateSellerCostResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/seller-costs/revisions`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateSellerCostResponse.parse(response);
  }

  async listReturns(params: Omit<T.ListReturnsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListReturnsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/returns`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListReturnsResponse.parse(response);
  }

  async listCalculations(params: Omit<T.ListCalculationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListCalculationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/calculations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCalculationsResponse.parse(response);
  }

  async listSalesPace(params: Omit<T.ListSalesPaceData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListSalesPaceResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/sales-pace`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListSalesPaceResponse.parse(response);
  }

  async listStocks(params: Omit<T.ListStocksData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListStocksResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/stock-pools`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListStocksResponse.parse(response);
  }

  async listCompetitors(params: Omit<T.ListCompetitorsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListCompetitorsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/competitor-observations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCompetitorsResponse.parse(response);
  }

  async createCompetitor(params: Omit<T.CreateCompetitorData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateCompetitorResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/competitor-observations`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateCompetitorResponse.parse(response);
  }

  async listMemberships(params: Omit<T.ListMembershipsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListMembershipsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/memberships`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListMembershipsResponse.parse(response);
  }

  async listAccountAccess(params: Omit<T.ListAccountAccessData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAccountAccessResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/account-access`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAccountAccessResponse.parse(response);
  }

  async listAudit(params: Omit<T.ListAuditData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAuditResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/audit`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAuditResponse.parse(response);
  }

  async listOperations(params: Omit<T.ListOperationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListOperationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/operations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListOperationsResponse.parse(response);
  }

  async listImports(params: Omit<T.ListImportsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListImportsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/imports`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListImportsResponse.parse(response);
  }

  async uploadImport(params: Omit<T.UploadImportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.UploadImportResponse> {
    const body = new FormData();
    body.append('file', params.body.file);
    body.append('kind', String(params.body.kind));
    body.append('clientRequestId', String(params.body.clientRequestId));
    body.append('expectedRevision', String(params.body.expectedRevision));
    body.append('delimiter', String(params.body.delimiter));
    body.append('decimalSeparator', String(params.body.decimalSeparator));
    if(params.body.sheetName!==undefined)body.append('sheetName', String(params.body.sheetName));
const response = await firstValueFrom(this.http.request("POST", `/api/v1/imports`, {
      body: body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zUploadImportResponse.parse(response);
  }

  async listReports(params: Omit<T.ListReportsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListReportsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/reports`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListReportsResponse.parse(response);
  }

  async createReport(params: Omit<T.CreateReportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateReportResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/reports`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateReportResponse.parse(response);
  }

  async listNotifications(params: Omit<T.ListNotificationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListNotificationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/notifications`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListNotificationsResponse.parse(response);
  }

  async getOffer(params: Omit<T.GetOfferData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetOfferResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/offers/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetOfferResponse.parse(response);
  }

  async getPolicy(params: Omit<T.GetPolicyData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetPolicyResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policies/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetPolicyResponse.parse(response);
  }

  async getDecision(params: Omit<T.GetDecisionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetDecisionResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/decisions/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetDecisionResponse.parse(response);
  }

  async getCommand(params: Omit<T.GetCommandData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetCommandResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/commands/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetCommandResponse.parse(response);
  }

  async getTemporaryRun(params: Omit<T.GetTemporaryRunData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetTemporaryRunResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/temporary-runs/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetTemporaryRunResponse.parse(response);
  }

  async getImport(params: Omit<T.GetImportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetImportResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/imports/${encodeURIComponent(params.path.id)}`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetImportResponse.parse(response);
  }

  async listPolicyVersions(params: Omit<T.ListPolicyVersionsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListPolicyVersionsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policies/${encodeURIComponent(params.path.id)}/versions`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListPolicyVersionsResponse.parse(response);
  }

  async getEconomicsSummary(params: Omit<T.GetEconomicsSummaryData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetEconomicsSummaryResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/economics/summary`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetEconomicsSummaryResponse.parse(response);
  }

  async getSafetyEnvelope(params: Omit<T.GetSafetyEnvelopeData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.GetSafetyEnvelopeResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/safety-envelopes/revisions`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetSafetyEnvelopeResponse.parse(response);
  }

  async saveSafetyEnvelope(params: Omit<T.SaveSafetyEnvelopeData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SaveSafetyEnvelopeResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/safety-envelopes/revisions`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSaveSafetyEnvelopeResponse.parse(response);
  }

  async getViewState(params: Omit<T.GetViewStateData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetViewStateResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/me/view-states/${encodeURIComponent(params.path.key)}`, {
      
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 15_000,
    }));
    return Z.zGetViewStateResponse.parse(response);
  }

  async saveViewState(params: Omit<T.SaveViewStateData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SaveViewStateResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/me/view-states/${encodeURIComponent(params.path.key)}`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 15_000,
    }));
    return Z.zSaveViewStateResponse.parse(response);
  }

  async resetViewState(params: Omit<T.ResetViewStateData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ResetViewStateResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/me/view-states/${encodeURIComponent(params.path.key)}/reset`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 15_000,
    }));
    return Z.zResetViewStateResponse.parse(response);
  }

  async savePolicyDraft(params: Omit<T.SavePolicyDraftData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SavePolicyDraftResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/policies/${encodeURIComponent(params.path.id)}/draft`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSavePolicyDraftResponse.parse(response);
  }

  async publishPolicy(params: Omit<T.PublishPolicyData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PublishPolicyResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policies/${encodeURIComponent(params.path.id)}/publish`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPublishPolicyResponse.parse(response);
  }

  async bulkAssign(params: Omit<T.BulkAssignData, 'headers'|'url'>, scope?: RequestScope): Promise<T.BulkAssignResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/bulk`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zBulkAssignResponse.parse(response);
  }

  async pauseAssignment(params: Omit<T.PauseAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PauseAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/pause`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPauseAssignmentResponse.parse(response);
  }

  async previewAssignment(params: Omit<T.PreviewAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PreviewAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/preview`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPreviewAssignmentResponse.parse(response);
  }

  async activateAssignment(params: Omit<T.ActivateAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ActivateAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/activate-auto`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zActivateAssignmentResponse.parse(response);
  }

  async createTaxRevision(params: Omit<T.CreateTaxRevisionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateTaxRevisionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/tax-profile/revisions`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateTaxRevisionResponse.parse(response);
  }

  async updateCompetitor(params: Omit<T.UpdateCompetitorData, 'headers'|'url'>, scope?: RequestScope): Promise<T.UpdateCompetitorResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/competitor-observations/${encodeURIComponent(params.path.id)}`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zUpdateCompetitorResponse.parse(response);
  }

  async inviteMember(params: Omit<T.InviteMemberData, 'headers'|'url'>, scope?: RequestScope): Promise<T.InviteMemberResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/invitations`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zInviteMemberResponse.parse(response);
  }

  async listInvitations(params: Omit<T.ListInvitationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListInvitationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/invitations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListInvitationsResponse.parse(response);
  }

  async acceptInvitation(params: Omit<T.AcceptInvitationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.AcceptInvitationResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/invitations/accept`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zAcceptInvitationResponse.parse(response);
  }

  async updateMembership(params: Omit<T.UpdateMembershipData, 'headers'|'url'>, scope?: RequestScope): Promise<T.UpdateMembershipResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/memberships/${encodeURIComponent(params.path.id)}`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zUpdateMembershipResponse.parse(response);
  }

  async revokeMembership(params: Omit<T.RevokeMembershipData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeMembershipResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/memberships/${encodeURIComponent(params.path.id)}/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeMembershipResponse.parse(response);
  }

  async updateAccountAccess(params: Omit<T.UpdateAccountAccessData, 'headers'|'url'>, scope?: RequestScope): Promise<T.UpdateAccountAccessResponse> {
    const response = await firstValueFrom(this.http.request("PUT", `/api/v1/account-access/${encodeURIComponent(params.path.id)}`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zUpdateAccountAccessResponse.parse(response);
  }

  async createSelection(params: Omit<T.CreateSelectionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateSelectionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/selections`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateSelectionResponse.parse(response);
  }

  async downloadReport(params: Omit<T.DownloadReportData, 'headers'|'url'>, scope?: RequestScope): Promise<Blob> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/reports/${encodeURIComponent(params.path.id)}/download`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'blob', timeout: 30_000,
    }));
    return response;
  }

  async applyImport(params: Omit<T.ApplyImportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ApplyImportResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/imports/${encodeURIComponent(params.path.id)}/apply`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zApplyImportResponse.parse(response);
  }

  async downloadImportErrors(params: Omit<T.DownloadImportErrorsData, 'headers'|'url'>, scope?: RequestScope): Promise<Blob> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/imports/${encodeURIComponent(params.path.id)}/errors`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'blob', timeout: 30_000,
    }));
    return response;
  }

  async previewDecision(params: Omit<T.PreviewDecisionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PreviewDecisionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/decisions/preview`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPreviewDecisionResponse.parse(response);
  }

  async previewFixedTarget(params: Omit<T.PreviewFixedTargetData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PreviewFixedTargetResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/offers/fixed-target/preview`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPreviewFixedTargetResponse.parse(response);
  }

  async approveDecision(params: Omit<T.ApproveDecisionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ApproveDecisionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/decisions/${encodeURIComponent(params.path.id)}/approve`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zApproveDecisionResponse.parse(response);
  }

  async reconcileCommand(params: Omit<T.ReconcileCommandData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReconcileCommandResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/commands/${encodeURIComponent(params.path.id)}/reconcile`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReconcileCommandResponse.parse(response);
  }

  async cancelCommand(params: Omit<T.CancelCommandData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CancelCommandResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/commands/${encodeURIComponent(params.path.id)}/cancel`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCancelCommandResponse.parse(response);
  }

  async createTemporaryRun(params: Omit<T.CreateTemporaryRunData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CreateTemporaryRunResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/temporary-runs`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCreateTemporaryRunResponse.parse(response);
  }

  async listTemporaryRuns(params: Omit<T.ListTemporaryRunsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListTemporaryRunsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/temporary-runs`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListTemporaryRunsResponse.parse(response);
  }

  async permitTemporaryRun(params: Omit<T.PermitTemporaryRunData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PermitTemporaryRunResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/temporary-runs/${encodeURIComponent(params.path.id)}/permission`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPermitTemporaryRunResponse.parse(response);
  }

  async getTemporaryPermission(params: Omit<T.GetTemporaryPermissionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetTemporaryPermissionResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/temporary-runs/${encodeURIComponent(params.path.id)}/permission`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetTemporaryPermissionResponse.parse(response);
  }

  async finishTemporaryRun(params: Omit<T.FinishTemporaryRunData, 'headers'|'url'>, scope?: RequestScope): Promise<T.FinishTemporaryRunResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/temporary-runs/${encodeURIComponent(params.path.id)}/finish`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zFinishTemporaryRunResponse.parse(response);
  }

  async readNotification(params: Omit<T.ReadNotificationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReadNotificationResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/notifications/${encodeURIComponent(params.path.id)}/read`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReadNotificationResponse.parse(response);
  }

  async readAllNotifications(params: Omit<T.ReadAllNotificationsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReadAllNotificationsResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/notifications/read-all`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReadAllNotificationsResponse.parse(response);
  }

  async getCurrentCost(params: Omit<T.GetCurrentCostData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetCurrentCostResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/cost-revisions/current/${encodeURIComponent(params.path.offerId)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetCurrentCostResponse.parse(response);
  }

  async getCurrentTax(params: Omit<T.GetCurrentTaxData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.GetCurrentTaxResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/tax-profile/revisions/current`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetCurrentTaxResponse.parse(response);
  }

  async getPauseState(params: Omit<T.GetPauseStateData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.GetPauseStateResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/automation/pause`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetPauseStateResponse.parse(response);
  }

  async changePause(params: Omit<T.ChangePauseData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ChangePauseResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/automation/pause`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zChangePauseResponse.parse(response);
  }

  async disconnectConnection(params: Omit<T.DisconnectConnectionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.DisconnectConnectionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/connections/disconnect`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zDisconnectConnectionResponse.parse(response);
  }

  async changePolicyStatus(params: Omit<T.ChangePolicyStatusData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ChangePolicyStatusResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policies/${encodeURIComponent(params.path.id)}/status`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zChangePolicyStatusResponse.parse(response);
  }

  async getOperation(params: Omit<T.GetOperationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetOperationResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/operations/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetOperationResponse.parse(response);
  }

  async getOfferBounds(params: Omit<T.GetOfferBoundsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetOfferBoundsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/offers/${encodeURIComponent(params.path.offerId)}/price-bounds`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetOfferBoundsResponse.parse(response);
  }

  async saveOfferBounds(params: Omit<T.SaveOfferBoundsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SaveOfferBoundsResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/offers/${encodeURIComponent(params.path.offerId)}/price-bounds`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSaveOfferBoundsResponse.parse(response);
  }

  async listPlacements(params: Omit<T.ListPlacementsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListPlacementsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/offers/${encodeURIComponent(params.path.id)}/placements`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListPlacementsResponse.parse(response);
  }

  async syncHistory(params: Omit<T.SyncHistoryData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SyncHistoryResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/history-sync`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSyncHistoryResponse.parse(response);
  }

  async syncReports(params: Omit<T.SyncReportsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.SyncReportsResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/report-sync`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zSyncReportsResponse.parse(response);
  }

  async reissueInvitation(params: Omit<T.ReissueInvitationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReissueInvitationResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/invitations/${encodeURIComponent(params.path.id)}/reissue`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReissueInvitationResponse.parse(response);
  }

  async revokeInvitation(params: Omit<T.RevokeInvitationData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeInvitationResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/invitations/${encodeURIComponent(params.path.id)}/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeInvitationResponse.parse(response);
  }

  async reactivateMembership(params: Omit<T.ReactivateMembershipData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReactivateMembershipResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/memberships/${encodeURIComponent(params.path.id)}/reactivate`, {
      body: params.body,
      
      headers: contextHeaders(scope, true), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReactivateMembershipResponse.parse(response);
  }

  async revokeAccountAccess(params: Omit<T.RevokeAccountAccessData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeAccountAccessResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/account-access/${encodeURIComponent(params.path.id)}/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeAccountAccessResponse.parse(response);
  }

  async getReport(params: Omit<T.GetReportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetReportResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/reports/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetReportResponse.parse(response);
  }

  async getAssignment(params: Omit<T.GetAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetAssignmentResponse.parse(response);
  }

  async getAutoGrant(params: Omit<T.GetAutoGrantData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetAutoGrantResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/auto-grant`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetAutoGrantResponse.parse(response);
  }

  async revokeAutoGrant(params: Omit<T.RevokeAutoGrantData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeAutoGrantResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/auto-grant/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeAutoGrantResponse.parse(response);
  }

  async revokeTemporaryPermission(params: Omit<T.RevokeTemporaryPermissionData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeTemporaryPermissionResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/temporary-runs/${encodeURIComponent(params.path.id)}/permission/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeTemporaryPermissionResponse.parse(response);
  }

  async previewAuto(params: Omit<T.PreviewAutoData, 'headers'|'url'>, scope?: RequestScope): Promise<T.PreviewAutoResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/auto-review`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zPreviewAutoResponse.parse(response);
  }

  async listQuantityComparisons(params: Omit<T.ListQuantityComparisonsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListQuantityComparisonsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/decisions/${encodeURIComponent(params.path.id)}/quantity-comparisons`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListQuantityComparisonsResponse.parse(response);
  }

  async compareQuantity(params: Omit<T.CompareQuantityData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CompareQuantityResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/decisions/${encodeURIComponent(params.path.id)}/quantity-comparisons`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCompareQuantityResponse.parse(response);
  }

  async revalidateImport(params: Omit<T.RevalidateImportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevalidateImportResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/imports/${encodeURIComponent(params.path.id)}/revalidate`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevalidateImportResponse.parse(response);
  }

  async cancelImport(params: Omit<T.CancelImportData, 'headers'|'url'>, scope?: RequestScope): Promise<T.CancelImportResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/imports/${encodeURIComponent(params.path.id)}/cancel`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zCancelImportResponse.parse(response);
  }

  async refreshSalesPace(params: Omit<T.RefreshSalesPaceData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RefreshSalesPaceResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/economics/sales-pace/refresh`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRefreshSalesPaceResponse.parse(response);
  }

  async getAssignmentBatch(params: Omit<T.GetAssignmentBatchData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetAssignmentBatchResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/assignment-batches/${encodeURIComponent(params.path.id)}`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetAssignmentBatchResponse.parse(response);
  }

  async listAssignmentBatchRows(params: Omit<T.ListAssignmentBatchRowsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListAssignmentBatchRowsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/assignment-batches/${encodeURIComponent(params.path.id)}/rows`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAssignmentBatchRowsResponse.parse(response);
  }

  async logout(params: Omit<T.LogoutData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.LogoutResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/auth/logout`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zLogoutResponse.parse(response);
  }

  async reviewTemporaryRun(params: Omit<T.ReviewTemporaryRunData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReviewTemporaryRunResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/temporary-runs/review`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReviewTemporaryRunResponse.parse(response);
  }

  async listCampaigns(params: Omit<T.ListCampaignsData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ListCampaignsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/marketplace-accounts/${encodeURIComponent(params.path.id)}/campaigns`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCampaignsResponse.parse(response);
  }

  async getSupplierPriceIndices(params: Omit<T.GetSupplierPriceIndicesData, 'headers'|'url'>, scope?: RequestScope): Promise<T.GetSupplierPriceIndicesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/offers/${encodeURIComponent(params.path.id)}/price-indices`, {
      
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zGetSupplierPriceIndicesResponse.parse(response);
  }

  async resumeAssignment(params: Omit<T.ResumeAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ResumeAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/resume`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zResumeAssignmentResponse.parse(response);
  }

  async listCompetitorSources(params: Omit<T.ListCompetitorSourcesData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListCompetitorSourcesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/competitor-observations/sources`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCompetitorSourcesResponse.parse(response);
  }

  async revokeCompetitor(params: Omit<T.RevokeCompetitorData, 'headers'|'url'>, scope?: RequestScope): Promise<T.RevokeCompetitorResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/competitor-observations/${encodeURIComponent(params.path.id)}/revoke`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zRevokeCompetitorResponse.parse(response);
  }

  async listReservations(params: Omit<T.ListReservationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListReservationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/reservations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListReservationsResponse.parse(response);
  }

  async listObligations(params: Omit<T.ListObligationsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListObligationsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/obligations`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListObligationsResponse.parse(response);
  }

  async listPromotions(params: Omit<T.ListPromotionsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListPromotionsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/promotions`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListPromotionsResponse.parse(response);
  }

  async listCategories(params: Omit<T.ListCategoriesData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListCategoriesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/categories`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListCategoriesResponse.parse(response);
  }

  async listWarehouses(params: Omit<T.ListWarehousesData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListWarehousesResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/warehouses`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListWarehousesResponse.parse(response);
  }

  async reviewAssignmentDetach(params: Omit<T.ReviewAssignmentDetachData, 'headers'|'url'>, scope?: RequestScope): Promise<T.ReviewAssignmentDetachResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/detach-review`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zReviewAssignmentDetachResponse.parse(response);
  }

  async detachAssignment(params: Omit<T.DetachAssignmentData, 'headers'|'url'>, scope?: RequestScope): Promise<T.DetachAssignmentResponse> {
    const response = await firstValueFrom(this.http.request("POST", `/api/v1/policy-assignments/${encodeURIComponent(params.path.id)}/detach`, {
      body: params.body,
      
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zDetachAssignmentResponse.parse(response);
  }

  async listAutomationSweeps(params: Omit<T.ListAutomationSweepsData, 'headers'|'url'> = {}, scope?: RequestScope): Promise<T.ListAutomationSweepsResponse> {
    const response = await firstValueFrom(this.http.request("GET", `/api/v1/automation-sweeps`, {
      
      params: queryParameters(params.query),
      headers: contextHeaders(scope, false), responseType: 'json', timeout: 30_000,
    }));
    return Z.zListAutomationSweepsResponse.parse(response);
  }
}
