// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zOrganization = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string().optional(),
    revision: z.int().optional()
});

export const zCurrentUser = z.object({
    userId: z.string(),
    displayName: z.string(),
    email: z.string(),
    organizations: z.array(zOrganization).max(1000),
    permissions: z.array(z.string()).max(1000)
});

export const zAccount = z.object({
    id: z.string(),
    name: z.string(),
    marketplace: z.enum(['OZON', 'YANDEX']),
    status: z.string(),
    keyConfigured: z.boolean(),
    revision: z.int(),
    externalId: z.string(),
    timezone: z.string().min(1).max(80)
});

export const zMutation = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int()
});

export const zOperation = z.object({
    operationId: z.string(),
    status: z.string(),
    message: z.string().optional()
});

export const zStrategy = z.enum([
    'HOLD_PRICE',
    'TARGET_PROFITABILITY',
    'FOLLOW_COMPETITOR'
]);

export const zCompetitorRule = z.object({
    aggregation: z.enum([
        'SELECTED_SELLER',
        'MIN',
        'SECOND',
        'MEDIAN',
        'MEAN'
    ]),
    selectedSource: z.string().nullish(),
    minimumSources: z.int(),
    segment: z.string(),
    amountOffset: z.string().nullish(),
    ratioOffset: z.string().nullish(),
    tolerance: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    maxAgeSeconds: z.int()
});

export const zPolicySchedule = z.object({
    days: z.array(z.enum([
        'MONDAY',
        'TUESDAY',
        'WEDNESDAY',
        'THURSDAY',
        'FRIDAY',
        'SATURDAY',
        'SUNDAY'
    ])).max(1000),
    start: z.string(),
    end: z.string(),
    zone: z.string()
});

export const zPolicyVersion = z.object({
    id: z.string(),
    version: z.int(),
    status: z.string(),
    createdAt: z.string(),
    actor: z.string()
});

export const zCostRevision = z.object({
    id: z.string(),
    offerId: z.string(),
    amount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    validFrom: z.string(),
    validTo: z.string().optional(),
    basis: z.string().optional(),
    createdAt: z.string(),
    actor: z.string(),
    revision: z.int(),
    extraExpense: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/)
});

export const zDecisionStep = z.object({
    id: z.string(),
    type: z.string(),
    description: z.string(),
    status: z.string()
});

export const zDecision = z.object({
    id: z.string(),
    offerId: z.string(),
    offerName: z.string().optional(),
    createdAt: z.string(),
    status: z.string(),
    strategy: z.string(),
    policyVersion: z.int(),
    currentPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    proposedPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    profit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    margin: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    reasons: z.array(z.string()).max(1000),
    steps: z.array(zDecisionStep).max(1000),
    revision: z.int(),
    commandId: z.string().optional(),
    sourceRevisions: z.record(z.string(), z.string()).optional(),
    placements: z.array(z.uuid()).max(200)
});

export const zCommandAttempt = z.object({
    id: z.string(),
    startedAt: z.string(),
    outcome: z.string(),
    message: z.string().optional()
});

export const zCommand = z.object({
    id: z.string(),
    decisionId: z.string(),
    offerId: z.string().optional(),
    status: z.string(),
    createdAt: z.string(),
    revision: z.int(),
    targetPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    effects: z.array(zDecisionStep).max(1000),
    attempts: z.array(zCommandAttempt).max(1000)
});

export const zFinanceRecord = z.object({
    id: z.string(),
    occurredAt: z.string(),
    name: z.string(),
    category: z.string(),
    amount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    status: z.enum([
        'UNKNOWN',
        'PRELIMINARY',
        'CONFIRMED',
        'INCOMPLETE'
    ]),
    offerId: z.string().optional(),
    source: z.string().optional(),
    revision: z.int(),
    income: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    cost: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    expenses: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    tax: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    profit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    complete: z.boolean(),
    certainty: z.enum([
        'UNKNOWN',
        'PRELIMINARY',
        'CONFIRMED'
    ])
});

export const zEconomicsCalculation = z.object({
    id: z.string(),
    offerId: z.string(),
    offerName: z.string(),
    sku: z.string(),
    decisionId: z.string().optional(),
    selectedCandidateId: z.string().optional(),
    status: z.string(),
    reason: z.string(),
    current: z.boolean(),
    calculatedAt: z.string().optional(),
    validUntil: z.string().optional(),
    price: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    cost: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    profit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    margin: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    currentPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    currentProfit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    revision: z.int().gte(0),
    sourceRevisions: z.record(z.string(), z.int().gte(0))
});

export const zStock = z.object({
    id: z.string(),
    offerId: z.string(),
    name: z.string(),
    warehouse: z.string(),
    physical: z.string().optional(),
    available: z.string().optional(),
    reserved: z.string().optional(),
    observedAt: z.string(),
    status: z.string()
});

export const zCompetitorObservation = z.object({
    id: z.uuid(),
    offerId: z.uuid(),
    sourceId: z.uuid(),
    sellerName: z.string().max(200),
    segment: z.string().max(1000),
    observedAt: z.iso.datetime(),
    inStock: z.boolean().nullish(),
    price: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    delivery: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    ownOffer: z.boolean(),
    revoked: z.boolean(),
    revision: z.int().gte(1),
    offerName: z.string()
});

export const zMembership = z.object({
    id: z.string(),
    displayName: z.string(),
    email: z.string(),
    role: z.string(),
    permissions: z.array(z.string()).max(1000),
    revision: z.int(),
    userId: z.string(),
    active: z.boolean()
});

export const zAuditRecord = z.object({
    id: z.string(),
    actorId: z.string().optional(),
    action: z.string(),
    targetId: z.string().optional(),
    details: z.string(),
    createdAt: z.string()
});

export const zBackgroundOperation = z.object({
    id: z.string(),
    name: z.string(),
    status: z.string(),
    createdAt: z.string(),
    progress: z.int().gte(0).lte(100).nullish(),
    message: z.string().optional(),
    resourceId: z.string().optional(),
    revision: z.int()
});

export const zNotification = z.object({
    id: z.string(),
    title: z.string(),
    message: z.string(),
    category: z.string(),
    createdAt: z.string(),
    read: z.boolean(),
    active: z.boolean().optional(),
    accountId: z.string().optional(),
    resourceType: z.string().optional(),
    resourceId: z.string().optional(),
    revision: z.int()
});

export const zSourceStatus = z.object({
    id: z.string(),
    name: z.string(),
    status: z.string(),
    lastSuccessAt: z.string().optional(),
    message: z.string().optional(),
    capabilities: z.array(z.object({
        name: z.string(),
        status: z.string(),
        reason: z.string().optional(),
        documented: z.boolean(),
        apiAvailable: z.boolean().optional(),
        executionVerified: z.boolean(),
        expiresAt: z.iso.datetime().optional()
    })).max(1000)
});

export const zSafetyEnvelope = z.object({
    revision: z.int(),
    minimumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    maximumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    minimumMargin: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    minimumProfit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    maximumOutcomeLoss: z.record(z.string(), z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/))
});

export const zViewState = z.object({
    query: z.object({
        search: z.string(),
        filters: z.record(z.string(), z.string()),
        sort: z.string(),
        page: z.int(),
        size: z.int()
    }),
    columns: z.object({
        order: z.array(z.string()).max(1000),
        hidden: z.array(z.string()).max(1000),
        widths: z.record(z.string(), z.int())
    }),
    presentation: z.object({
        expanded: z.array(z.string()).max(1000)
    }),
    navigation: z.object({
        collapsed: z.boolean()
    })
});

export const zSavedView = z.object({
    revision: z.int(),
    resetGeneration: z.int(),
    state: zViewState,
    schemaVersion: z.int()
});

export const zSelection = z.object({
    id: z.string(),
    total: z.int(),
    expiresAt: z.string()
});

export const zProblem = z.object({
    code: z.string(),
    message: z.string(),
    status: z.int(),
    requestId: z.string()
});

export const zCsrf = z.object({
    token: z.string().optional(),
    headerName: z.string().optional()
});

export const zOrganizationRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    name: z.string().min(1).max(160)
});

export const zAccountRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    name: z.string(),
    marketplace: z.enum(['OZON', 'YANDEX']),
    externalId: z.string(),
    timezone: z.string().min(1).max(80)
});

export const zCostRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    offerId: z.string(),
    amount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    extraExpense: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    validFrom: z.string(),
    validTo: z.string().nullish()
});

export const zCompetitorRequest = z.object({
    clientRequestId: z.uuid(),
    expectedRevision: z.int().gte(0),
    offerId: z.uuid(),
    sourceId: z.uuid(),
    sellerName: z.string().max(200),
    segment: z.string().max(1000),
    observedAt: z.iso.datetime(),
    inStock: z.boolean().nullable(),
    price: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullable(),
    delivery: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullable(),
    ownOffer: z.boolean()
});

export const zInvitationRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    email: z.email(),
    role: z.enum(['ADMIN', 'MEMBER'])
});

export const zInvitationAccept = z.object({
    clientRequestId: z.uuid(),
    token: z.string().max(256)
});

export const zAccessRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    role: z.string(),
    permissions: z.array(z.string()).max(1000)
});

export const zSavedViewRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    resetGeneration: z.int(),
    state: zViewState
});

export const zSelectionRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    resource: z.string(),
    query: z.object({
        search: z.string().max(512),
        filters: z.record(z.string(), z.string().max(512)),
        sort: z.string(),
        page: z.int().gte(0),
        size: z.int().gte(1).lte(200)
    }),
    ids: z.array(z.string()).max(1000).optional()
});

export const zReportRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    selectionId: z.string(),
    format: z.enum(['CSV', 'XLSX']),
    kind: z.enum([
        'EXPORT',
        'MONTHLY_PNL',
        'MONTHLY_UNIT_ECONOMICS',
        'RETURNS',
        'INVENTORY'
    ]).optional()
});

export const zPreviewRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    offerId: z.string()
});

export const zFixedTargetRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    offerId: z.string(),
    priceKind: z.enum([
        'BASE_SELLER',
        'EFFECTIVE_SELLER',
        'BUYER_TOTAL'
    ]),
    target: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    targetId: z.uuid().optional()
});

export const zSafetyRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    minimumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    maximumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    minimumMargin: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    minimumProfit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    maximumOutcomeLoss: z.record(z.string(), z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/))
});

export const zTaxRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    rate: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    validFrom: z.string(),
    validTo: z.string().nullish()
});

export const zTemporaryRunRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    assignmentId: z.string(),
    offerIds: z.array(z.uuid()).min(1).max(1000),
    startsAt: z.string(),
    endsAt: z.string(),
    maximumAcceptedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    minimumRemainingStock: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    expectedCompletionReviewDigest: z.string().length(64).regex(/^[a-f0-9]{64}$/)
});

export const zTemporaryPermissionRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    keptProfitFloor: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    lossBudget: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish()
});

export const zImportDetail = z.object({
    id: z.string(),
    name: z.string(),
    status: z.string(),
    revision: z.int(),
    totalRows: z.int(),
    validRows: z.int(),
    errorRows: z.int(),
    rows: z.array(z.object({
        row: z.int(),
        status: z.string(),
        message: z.string().optional()
    })).max(200),
    reason: z.string().optional(),
    validationEdition: z.int().gte(1),
    temporaryExpired: z.boolean()
});

export const zTransferOwnerRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    memberId: z.string()
});

export const zBulkAssignmentRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    selectionId: z.string(),
    policyId: z.string(),
    mode: z.enum(['PREVIEW', 'MANUAL'])
});

export const zImportApplyRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    previewRevision: z.int()
});

export const zAccountPage = z.object({
    items: z.array(zAccount).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zSourceStatusPage = z.object({
    items: z.array(zSourceStatus).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zCostRevisionPage = z.object({
    items: z.array(zCostRevision).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zFinanceRecordPage = z.object({
    items: z.array(zFinanceRecord).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zEconomicsCalculationPage = z.object({
    items: z.array(zEconomicsCalculation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zStockPage = z.object({
    items: z.array(zStock).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zCompetitorObservationPage = z.object({
    items: z.array(zCompetitorObservation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zMembershipPage = z.object({
    items: z.array(zMembership).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zAuditRecordPage = z.object({
    items: z.array(zAuditRecord).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zBackgroundOperationPage = z.object({
    items: z.array(zBackgroundOperation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zNotificationPage = z.object({
    items: z.array(zNotification).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zPolicyVersionPage = z.object({
    items: z.array(zPolicyVersion).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zNonCompetitiveRule = z.object({
    strategy: z.enum(['HOLD_PRICE', 'TARGET_PROFITABILITY']),
    priceKind: z.enum([
        'BASE_SELLER',
        'EFFECTIVE_SELLER',
        'BUYER_TOTAL'
    ]),
    target: z.string().nullish(),
    corridorMinimum: z.string().nullish(),
    corridorMaximum: z.string().nullish(),
    metric: z.union([
        z.literal('PROFIT'),
        z.literal('MARGIN')
    ]).nullish(),
    unreachable: z.enum(['KEEP_SAFE', 'NEAREST_SAFE']),
    competitor: z.null(),
    reserve: z.null(),
    promoMode: z.enum([
        'PRESERVE',
        'CONSIDER',
        'ENSURE_SELECTED',
        'FORBID_SELECTED'
    ]),
    selectedPromos: z.array(z.string()).max(1000),
    protectedPromos: z.array(z.string()).max(1000),
    allowedCombinations: z.array(z.array(z.uuid()).max(8)).max(16).optional(),
    discoveryProfiles: z.array(z.object({
        id: z.uuid(),
        revision: z.int().gte(1)
    })).max(500).optional(),
    excludedPromos: z.array(z.uuid()).max(500).optional()
});

export const zRule = z.object({
    strategy: zStrategy,
    priceKind: z.enum([
        'BASE_SELLER',
        'EFFECTIVE_SELLER',
        'BUYER_TOTAL'
    ]),
    target: z.string().nullish(),
    corridorMinimum: z.string().nullish(),
    corridorMaximum: z.string().nullish(),
    metric: z.union([
        z.literal('PROFIT'),
        z.literal('MARGIN')
    ]).nullish(),
    unreachable: z.enum(['KEEP_SAFE', 'NEAREST_SAFE']),
    competitor: zCompetitorRule.nullish(),
    reserve: zNonCompetitiveRule.nullish(),
    promoMode: z.enum([
        'PRESERVE',
        'CONSIDER',
        'ENSURE_SELECTED',
        'FORBID_SELECTED'
    ]),
    selectedPromos: z.array(z.string()).max(1000),
    protectedPromos: z.array(z.string()).max(1000),
    allowedCombinations: z.array(z.array(z.uuid()).max(8)).max(16).optional(),
    discoveryProfiles: z.array(z.object({
        id: z.uuid(),
        revision: z.int().gte(1)
    })).max(500).optional(),
    excludedPromos: z.array(z.uuid()).max(500).optional()
});

export const zPolicySettings = z.object({
    regularRule: zRule,
    temporaryRule: zRule.optional(),
    allowedOperations: z.array(z.enum([
        'SET_BASE_PRICE',
        'SET_PROMO_PRICE',
        'JOIN_PROMO',
        'LEAVE_PROMO'
    ])).max(1000),
    stockProtection: z.object({
        enabled: z.boolean(),
        floor: z.string(),
        recoveryQuantity: z.string(),
        raiseRatio: z.string().optional()
    }),
    stability: z.object({
        significantStep: z.string(),
        maximumStep: z.string(),
        movementBudget: z.string(),
        movementWindowSeconds: z.int(),
        maximumCommands: z.int(),
        pauseSeconds: z.int(),
        decisionAgeSeconds: z.int(),
        writerMode: z.union([
            z.literal('REQUIRE_CONDITIONAL'),
            z.literal('DECLARED_EXCLUSIVE_WRITER')
        ]).nullable(),
        maximumConsecutiveDecreases: z.int().optional()
    }),
    schedule: z.array(zPolicySchedule).max(1000),
    allowProtectiveCorrection: z.boolean()
});

export const zPolicy = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    status: z.string(),
    version: z.int(),
    revision: z.int(),
    settings: zPolicySettings,
    assignmentsCount: z.int().nullish(),
    hasDraft: z.boolean().optional(),
    draft: zPolicySettings.optional(),
    assignmentScopes: z.array(z.enum([
        'ACCOUNT',
        'CATEGORY',
        'OFFER'
    ])).max(3).nullish()
});

export const zPolicyRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    name: z.string().min(1).max(120),
    description: z.string(),
    settings: zPolicySettings
});

export const zPolicyPage = z.object({
    items: z.array(zPolicy).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zAccountAccess = z.object({
    active: z.boolean(),
    userId: z.string(),
    role: z.string(),
    permissions: z.array(z.string()).max(100),
    id: z.string(),
    revision: z.int(),
    displayName: z.string(),
    email: z.string()
});

export const zAccountAccessPage = z.object({
    size: z.int(),
    items: z.array(zAccountAccess).max(200),
    total: z.int(),
    page: z.int()
});

export const zInvitation = z.object({
    id: z.string(),
    email: z.string(),
    role: z.string(),
    permissions: z.array(z.string()),
    expiresAt: z.string(),
    consumedAt: z.string().nullish(),
    revokedAt: z.string().nullish(),
    revision: z.int(),
    mailState: z.string()
});

export const zAcceptedInvitation = z.object({
    organizationId: z.string(),
    accountId: z.string().nullish(),
    membershipId: z.string(),
    accountAccessId: z.string().nullish()
});

export const zInvitationPage = z.object({
    items: z.array(zInvitation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zLocalReferences = z.object({
    selectedPromos: z.array(z.string()).max(500),
    protectedPromos: z.array(z.string()).max(500),
    competitorSource: z.string().nullish(),
    allowedCombinations: z.array(z.array(z.uuid()).max(8)).max(16).optional(),
    discoveryProfiles: z.array(z.object({
        id: z.uuid(),
        revision: z.int().gte(1)
    })).max(500).optional(),
    excludedPromos: z.array(z.uuid()).max(500).optional()
});

export const zAssignment = z.object({
    id: z.string(),
    policyId: z.string(),
    accountId: z.string(),
    scope: z.enum([
        'ACCOUNT',
        'CATEGORY',
        'OFFER'
    ]),
    targetId: z.string().optional(),
    targetName: z.string().optional(),
    mode: z.enum([
        'PREVIEW',
        'MANUAL',
        'AUTO'
    ]),
    status: z.string(),
    revision: z.int(),
    temporaryRunId: z.string().optional(),
    regularReferences: zLocalReferences,
    temporaryReferences: zLocalReferences
});

export const zAssignmentRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    policyId: z.string(),
    accountId: z.string(),
    scope: z.enum([
        'ACCOUNT',
        'CATEGORY',
        'OFFER'
    ]),
    targetId: z.string().nullish(),
    mode: z.enum([
        'PREVIEW',
        'MANUAL',
        'AUTO'
    ]),
    regularReferences: zLocalReferences,
    temporaryReferences: zLocalReferences
});

export const zAssignmentPage = z.object({
    items: z.array(zAssignment).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zCostInterval = z.object({
    validFrom: z.string(),
    validUntil: z.string().optional(),
    amount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    extraExpense: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/)
});

export const zCostView = z.object({
    offerId: z.string(),
    revision: z.int(),
    intervals: z.array(zCostInterval).max(1000)
});

export const zTaxInterval = z.object({
    validFrom: z.string(),
    validUntil: z.string().optional(),
    rate: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/)
});

export const zTaxView = z.object({
    revision: z.int(),
    intervals: z.array(zTaxInterval).max(1000)
});

export const zPauseState = z.object({
    offerId: z.string().optional(),
    paused: z.boolean(),
    revision: z.int()
});

export const zPauseRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    offerId: z.string().nullish(),
    paused: z.boolean()
});

export const zConnectionView = z.object({
    configured: z.boolean(),
    state: z.string(),
    readOnly: z.boolean(),
    revision: z.int(),
    checkedAt: z.string().optional()
});

export const zConnectionRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    secret: z.string().max(4096),
    readOnly: z.boolean()
});

export const zPayment = z.object({
    id: z.string(),
    externalId: z.string(),
    occurredAt: z.string(),
    amount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    currency: z.string(),
    scope: z.string(),
    rawFileId: z.string(),
    revision: z.int()
});

export const zPaymentPage = z.object({
    items: z.array(zPayment).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zReturnRecord = z.object({
    id: z.string(),
    offerId: z.string(),
    lineId: z.string(),
    returnedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    returnedAt: z.string(),
    refundConfirmed: z.boolean().optional(),
    refundedAmount: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    physicalReceiptConfirmed: z.boolean().optional(),
    resalable: z.boolean().optional(),
    stockConfirmed: z.boolean().optional(),
    rawFileId: z.string(),
    revision: z.int()
});

export const zReturnRecordPage = z.object({
    items: z.array(zReturnRecord).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zPolicyStatusRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    status: z.enum([
        'ACTIVE',
        'PAUSED',
        'ARCHIVED'
    ])
});

export const zOfferBounds = z.object({
    offerId: z.string(),
    revision: z.int().gte(0),
    enabled: z.boolean(),
    minimumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    maximumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional()
});

export const zOfferBoundsRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    enabled: z.boolean(),
    minimumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    maximumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish()
});

export const zPlacement = z.object({
    id: z.string(),
    externalId: z.string(),
    model: z.string(),
    status: z.string(),
    available: z.boolean().optional(),
    revision: z.int().gte(0),
    observedAt: z.string(),
    validUntil: z.string()
});

export const zPlacementPage = z.object({
    items: z.array(zPlacement).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zHistorySyncRequest = z.object({
    clientRequestId: z.uuid(),
    from: z.iso.date(),
    until: z.iso.date()
});

export const zImportSummary = z.object({
    id: z.string(),
    name: z.string(),
    status: z.string(),
    kind: z.string(),
    createdAt: z.string(),
    revision: z.int().gte(0),
    totalRows: z.int().gte(0),
    errorRows: z.int().gte(0),
    reason: z.string().optional(),
    validationEdition: z.int().gte(1),
    temporaryExpired: z.boolean()
});

export const zImportSummaryPage = z.object({
    items: z.array(zImportSummary).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zEconomicPermission = z.object({
    id: z.string(),
    runId: z.string(),
    revision: z.int().gte(0),
    startsAt: z.string(),
    endsAt: z.string(),
    keptProfitFloor: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    lossBudget: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    boundedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    externalBoundaryEvidence: z.string().optional(),
    scopeDigest: z.string(),
    status: z.string(),
    allowedOperations: z.array(z.enum([
        'SET_PRICE',
        'SET_PROMO_PRICE',
        'JOIN_PROMO',
        'LEAVE_PROMO'
    ])).max(4)
});

export const zReportSyncRequest = z.object({
    clientRequestId: z.uuid(),
    from: z.iso.date(),
    until: z.iso.date(),
    kind: z.enum([
        'PAYMENTS',
        'RETURNS',
        'SERVICES',
        'REALIZATION'
    ]),
    campaignId: z.string().min(1).max(20).regex(/^[0-9]+$/).optional()
});

export const zReportSummary = z.object({
    id: z.string(),
    name: z.string(),
    status: z.string(),
    createdAt: z.string(),
    message: z.string().optional(),
    revision: z.int().gte(0),
    format: z.enum(['CSV', 'XLSX']),
    rowCount: z.int().gte(0),
    expiresAt: z.string().optional(),
    fileId: z.string().optional(),
    operationId: z.string(),
    dataStatus: z.enum([
        'AS_PUBLISHED',
        'COMPLETE',
        'INCOMPLETE'
    ]).optional()
});

export const zReportSummaryPage = z.object({
    items: z.array(zReportSummary).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zAutoGrantBinding = z.object({
    assignmentId: z.string(),
    assignmentRevision: z.int().gte(0),
    policyVersion: z.int().gte(0),
    scopeDigest: z.string(),
    operations: z.array(z.string()).max(4),
    targetIds: z.array(z.string()).max(1000)
});

export const zAutoGrant = z.object({
    id: z.string(),
    issuerId: z.string(),
    revision: z.int().gte(0),
    binding: zAutoGrantBinding,
    active: z.boolean(),
    createdAt: z.string()
});

export const zAutoGrantState = z.object({
    grant: zAutoGrant.optional()
});

export const zAutoActivationRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    expectedGrantRevision: z.int().gte(0),
    expectedPolicyVersion: z.int().gte(1),
    expectedScopeDigest: z.string().regex(/^[0-9a-f]{64}$/)
});

export const zRiskUsage = z.object({
    recognizedLoss: z.string().regex(/^-?[0-9]+(?:\.[0-9]+)?$/),
    potentialLoss: z.string().regex(/^-?[0-9]+(?:\.[0-9]+)?$/),
    occupied: z.string().regex(/^-?[0-9]+(?:\.[0-9]+)?$/),
    remaining: z.string().regex(/^-?[0-9]+(?:\.[0-9]+)?$/).optional()
});

export const zTemporaryPermissionState = z.object({
    permission: zEconomicPermission.optional(),
    usage: zRiskUsage.optional()
});

export const zPermissionRevocationRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    expectedPermissionRevision: z.int().gte(0)
});

export const zAutoActivationReview = z.object({
    assignmentId: z.string(),
    assignmentRevision: z.int().gte(0),
    policyVersion: z.int().gte(0),
    scopeDigest: z.string(),
    operations: z.array(z.string()).max(4),
    targetIds: z.array(z.string()).max(1000),
    targetsCount: z.int().gte(1).lte(1000)
});

export const zQuantityScenario = z.object({
    quantity: z.int(),
    result: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    difference: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/)
});

export const zQuantityResult = z.object({
    baselineQuantity: z.int(),
    baselineResult: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    scenarios: z.array(zQuantityScenario).max(4),
    thresholdStatus: z.enum([
        'FOUND',
        'NO_FINITE_THRESHOLD',
        'LIMIT_EXCEEDED'
    ]),
    threshold: z.int().optional(),
    reachableWithStock: z.boolean().optional(),
    hypotheticalBaseline: z.boolean(),
    relativeQuantityChangePercent: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional()
});

export const zQuantityComparison = z.object({
    id: z.uuid(),
    decisionId: z.uuid(),
    placementId: z.uuid().optional(),
    createdAt: z.string(),
    baselineQuantity: z.int(),
    status: z.enum(['COMPLETE', 'INCOMPLETE']),
    reason: z.string(),
    baselineCandidateId: z.uuid().optional(),
    candidateId: z.uuid().optional(),
    availableQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    baselineUnitProfit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    candidateUnitProfit: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    comparison: zQuantityResult.optional(),
    condition: z.enum(['KEPT_PURCHASE']),
    stockRevision: z.int(),
    stockObservedAt: z.string().optional(),
    sourceRevisions: z.record(z.string(), z.int())
});

export const zQuantityComparisonPage = z.object({
    items: z.array(zQuantityComparison).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zQuantityRequest = z.object({
    clientRequestId: z.uuid(),
    placementId: z.uuid(),
    quantity: z.int().gte(1).lte(1000000)
});

export const zAssignmentBatch = z.object({
    id: z.uuid(),
    kind: z.enum(['ASSIGN', 'PREVIEW']),
    selectionId: z.uuid().optional(),
    assignmentId: z.uuid().optional(),
    assignmentRevision: z.int().gte(0),
    policyId: z.uuid(),
    policyVersion: z.int().gte(0),
    mode: z.string(),
    state: z.string(),
    total: z.int().gte(0),
    captured: z.int().gte(0),
    cursor: z.uuid().optional(),
    applied: z.int().gte(0),
    failed: z.int().gte(0),
    waiting: z.int().gte(0),
    createdAt: z.iso.datetime()
});

export const zAssignmentBatchRow = z.object({
    id: z.uuid(),
    offerId: z.uuid(),
    state: z.string(),
    reason: z.string().optional(),
    operationId: z.uuid().optional(),
    assignmentId: z.uuid().optional(),
    assignmentRevision: z.int().gte(0),
    targetId: z.uuid().optional()
});

export const zAssignmentBatchRowPage = z.object({
    items: z.array(zAssignmentBatchRow).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zAccountAccessRequest = z.object({
    clientRequestId: z.string(),
    expectedRevision: z.int().nullish(),
    role: z.string(),
    permissions: z.array(z.string()).max(1000)
});

export const zLogoutResult = z.object({
    redirectUrl: z.enum(['/'])
});

export const zTemporaryRunReviewRequest = z.object({
    expectedRevision: z.int(),
    assignmentId: z.string(),
    offerIds: z.array(z.uuid()).min(1).max(1000),
    startsAt: z.string(),
    endsAt: z.string(),
    maximumAcceptedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish(),
    minimumRemainingStock: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).nullish()
});

export const zTemporaryRunCompletionTarget = z.object({
    offerId: z.uuid(),
    targetId: z.uuid(),
    possibleExits: z.array(z.uuid()).max(500),
    managedFields: z.array(z.string().max(200)).max(1000)
});

export const zTemporaryRunCompletionReview = z.object({
    firstActiveAt: z.iso.datetime(),
    earliestCompletionAt: z.iso.datetime(),
    digest: z.string().length(64),
    targets: z.array(zTemporaryRunCompletionTarget).max(1000)
});

export const zTemporaryRun = z.object({
    id: z.string(),
    assignmentId: z.string(),
    assignmentRevision: z.int().gte(0),
    policyId: z.string(),
    policyVersion: z.int().gte(0),
    state: z.enum([
        'READY',
        'RUNNING',
        'FINISHING',
        'FINISHED'
    ]),
    startsAt: z.string(),
    endsAt: z.string(),
    maximumAcceptedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    minimumRemainingStock: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    acceptedQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    scopeDigest: z.string(),
    reason: z.string(),
    revision: z.int().gte(0),
    completionReview: zTemporaryRunCompletionReview.nullish()
});

export const zTemporaryRunPage = z.object({
    items: z.array(zTemporaryRun).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zCampaign = z.object({
    id: z.string().max(20),
    placementType: z.string(),
    status: z.string()
});

export const zCampaignPage = z.object({
    items: z.array(zCampaign).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zOfferPromotion = z.object({
    id: z.uuid(),
    targetId: z.uuid(),
    name: z.string(),
    processing: z.boolean()
});

export const zPriceComparison = z.object({
    buyerPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    referencePrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    placementId: z.uuid(),
    segment: z.string().max(1000),
    observations: z.array(z.uuid()).max(500),
    calculatedAt: z.iso.datetime(),
    validUntil: z.iso.datetime()
});

export const zOffer = z.object({
    id: z.string(),
    sku: z.string(),
    name: z.string(),
    imageUrl: z.string().optional(),
    sellerPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    buyerPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    cost: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    costFrom: z.string().optional(),
    costTo: z.string().optional(),
    policyName: z.string().optional(),
    lastCalculationAt: z.string().optional(),
    lastDecisionId: z.string().optional(),
    lastCommandId: z.string().optional(),
    commandState: z.string().optional(),
    margin: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    commission: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    stock: z.string().optional(),
    revision: z.int(),
    currency: z.string().optional(),
    observedAt: z.string().optional(),
    policyId: z.uuid().optional(),
    mode: z.string().optional(),
    assignmentStatus: z.string().optional(),
    decisionStatus: z.string().optional(),
    promotions: z.array(zOfferPromotion).max(100).optional(),
    priceTargets: z.array(z.uuid()).max(200).optional(),
    priceIndex: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    priceComparison: zPriceComparison.optional()
});

export const zOfferPage = z.object({
    items: z.array(zOffer).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zSupplierIndex = z.object({
    value: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    minimumPrice: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    currency: z.string().max(10).optional()
});

export const zSupplierPriceIndices = z.object({
    source: z.string().optional(),
    color: z.string().optional(),
    ozon: zSupplierIndex,
    external: zSupplierIndex
});

export const zPaceInventoryPool = z.object({
    poolId: z.string(),
    availableQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    revision: z.int(),
    observedAt: z.string().optional(),
    validUntil: z.string().optional(),
    placementCount: z.int().gte(0)
});

export const zPaceCurrentInventory = z.object({
    assessedAt: z.string(),
    poolCount: z.int().gte(0),
    pools: z.array(zPaceInventoryPool).max(200),
    stockDurationDays: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    reason: z.string()
});

export const zSalesPace = z.object({
    id: z.string(),
    offerId: z.string(),
    placementId: z.string(),
    offerName: z.string(),
    status: z.string(),
    reason: z.string(),
    revision: z.int(),
    period: z.string(),
    observedRate: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    quantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    observedDays: z.int(),
    observedSeconds: z.int(),
    orderedUnits: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    calculatedAt: z.string(),
    futureStart: z.string(),
    futureEnd: z.string(),
    validUntil: z.string(),
    sourceIds: z.array(z.string()).max(100),
    currentInventory: zPaceCurrentInventory.optional()
});

export const zSalesPacePage = z.object({
    items: z.array(zSalesPace).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zCompetitorSource = z.object({
    sourceId: z.uuid(),
    sellerName: z.string()
});

export const zCompetitorSourcePage = z.object({
    items: z.array(zCompetitorSource).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zQuantityReservation = z.object({
    commandId: z.uuid(),
    poolId: z.uuid(),
    offerId: z.uuid(),
    quantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    state: z.enum([
        'HELD',
        'CONVERTED',
        'RELEASED'
    ]),
    stockRevision: z.int().gte(0)
});

export const zQuantityObligation = z.object({
    id: z.uuid(),
    commandId: z.uuid(),
    poolId: z.uuid(),
    offerId: z.uuid(),
    quantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/),
    state: z.enum([
        'EXPECTED',
        'CONFIRMED',
        'DISPUTED',
        'SETTLED',
        'CANCELLED'
    ]),
    reflectedInStock: z.boolean(),
    reflectedStockRevision: z.int().gte(0).optional(),
    sourceRevision: z.int().gte(0).optional(),
    observedAt: z.iso.datetime().optional(),
    remainingQuantity: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    admissionClosed: z.boolean().optional()
});

export const zQuantityReservationPage = z.object({
    items: z.array(zQuantityReservation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zQuantityObligationPage = z.object({
    items: z.array(zQuantityObligation).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zDailyIncome = z.object({
    date: z.iso.date(),
    income: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    events: z.int().gte(0),
    complete: z.boolean()
});

export const zEconomicsSummary = z.object({
    period: z.string(),
    status: z.string(),
    revenue: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    costs: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    result: z.string().max(80).regex(/^-?[0-9]+(\.[0-9]+)?$/).optional(),
    completeness: z.string(),
    lines: z.array(z.object({
        id: z.string(),
        name: z.string(),
        amount: z.string().optional()
    })).max(1000),
    unknownReasons: z.array(z.string()).max(1000),
    sections: z.array(z.object({
        id: z.string(),
        name: z.string(),
        events: z.int().gte(0),
        lines: z.array(z.object({
            id: z.string(),
            name: z.string(),
            amount: z.string().optional()
        })).max(1000)
    })).max(4),
    daily: z.array(zDailyIncome).min(28).max(31)
});

export const zPromotion = z.object({
    id: z.uuid(),
    name: z.string(),
    type: z.string(),
    startsAt: z.iso.datetime(),
    endsAt: z.iso.datetime(),
    processing: z.boolean().nullable(),
    revision: z.int(),
    validUntil: z.iso.datetime()
});

export const zCategory = z.object({
    id: z.uuid(),
    externalId: z.string(),
    name: z.string(),
    kind: z.enum(['CATEGORY', 'TYPE']),
    parentId: z.uuid().nullable(),
    disabled: z.boolean(),
    revision: z.int(),
    observedAt: z.iso.datetime(),
    validUntil: z.iso.datetime()
});

export const zWarehouse = z.object({
    id: z.uuid(),
    externalId: z.string(),
    name: z.string(),
    model: z.string(),
    campaignId: z.string().nullable(),
    groupId: z.string().nullable(),
    models: z.array(z.string()).max(20),
    observedAt: z.iso.datetime()
});

export const zPromotionPage = z.object({
    items: z.array(zPromotion).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zCategoryPage = z.object({
    items: z.array(zCategory).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zWarehousePage = z.object({
    items: z.array(zWarehouse).max(200),
    total: z.int(),
    page: z.int(),
    size: z.int()
});

export const zInheritedRule = z.object({
    assignmentId: z.uuid(),
    assignmentRevision: z.int(),
    policyId: z.uuid(),
    policyName: z.string(),
    policyVersion: z.int(),
    policyRevision: z.int(),
    scope: z.enum(['CATEGORY', 'ACCOUNT']),
    targetId: z.uuid(),
    mode: z.enum([
        'PREVIEW',
        'MANUAL',
        'AUTO'
    ]),
    status: z.string()
});

export const zAssignmentDetachReview = z.object({
    assignmentId: z.uuid(),
    assignmentRevision: z.int(),
    inherited: zInheritedRule.nullable(),
    reason: z.string(),
    digest: z.string().length(64)
});

export const zAssignmentDetachRequest = z.object({
    clientRequestId: z.uuid(),
    expectedRevision: z.int().gte(1),
    expectedInheritanceDigest: z.string().length(64)
});

export const zAutomationSweep = z.object({
    accountId: z.uuid(),
    cycle: z.int().gte(1),
    completedCycles: z.int().gte(0),
    cycleStartedAt: z.iso.datetime().optional()
});

export const zAutomationSweepPage = z.object({
    items: z.array(zAutomationSweep).max(200),
    total: z.int().gte(0),
    page: z.int().gte(0),
    size: z.int().gte(1).lte(200)
});

export const zGetMeHeaders = z.object({
    'X-Organization-Id': z.string().optional()
});

/**
 * Success
 */
export const zGetMeResponse = zCurrentUser;

/**
 * Success
 */
export const zGetCsrfResponse = zCsrf;

export const zCreateOrganizationBody = zOrganizationRequest;

/**
 * Success
 */
export const zCreateOrganizationResponse = zOrganization;

export const zUpdateOrganizationBody = zOrganizationRequest;

export const zUpdateOrganizationHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zUpdateOrganizationPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zUpdateOrganizationResponse = zOrganization;

export const zTransferOwnerBody = zTransferOwnerRequest;

export const zTransferOwnerHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zTransferOwnerPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zTransferOwnerResponse = zOrganization;

export const zListAccountsHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zListAccountsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListAccountsResponse = zAccountPage;

export const zCreateAccountBody = zAccountRequest;

export const zCreateAccountHeaders = z.object({
    'X-Organization-Id': z.string()
});

/**
 * Success
 */
export const zCreateAccountResponse = zAccount;

export const zGetConnectionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetConnectionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetConnectionResponse = zConnectionView;

export const zSaveConnectionBody = zConnectionRequest;

export const zSaveConnectionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zSaveConnectionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zSaveConnectionResponse = zConnectionView;

export const zListSourcesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListSourcesPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zListSourcesResponse = zSourceStatusPage;

export const zCheckConnectionBody = zMutation;

export const zCheckConnectionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zCheckConnectionPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zCheckConnectionResponse = zOperation;

export const zSyncAccountBody = zMutation;

export const zSyncAccountHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zSyncAccountPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zSyncAccountResponse = zOperation;

export const zListOffersHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListOffersQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    name: z.string().max(512).optional(),
    sku: z.string().max(512).optional(),
    policy: z.string().max(512).optional(),
    policyId: z.string().max(512).optional(),
    decisionId: z.string().max(512).optional(),
    commandId: z.string().max(512).optional(),
    offerId: z.string().max(512).optional(),
    mode: z.string().max(512).optional(),
    assignmentStatus: z.string().max(512).optional(),
    decisionStatus: z.string().max(512).optional(),
    commandState: z.string().max(512).optional(),
    costFrom: z.string().max(512).optional(),
    costTo: z.string().max(512).optional(),
    runFrom: z.string().max(512).optional(),
    runTo: z.string().max(512).optional(),
    priceMin: z.string().max(512).optional(),
    priceMax: z.string().max(512).optional(),
    buyerMin: z.string().max(512).optional(),
    buyerMax: z.string().max(512).optional(),
    costMin: z.string().max(512).optional(),
    costMax: z.string().max(512).optional(),
    commissionMin: z.string().max(512).optional(),
    commissionMax: z.string().max(512).optional(),
    marginMin: z.string().max(512).optional(),
    marginMax: z.string().max(512).optional(),
    stockMin: z.string().max(512).optional(),
    stockMax: z.string().max(512).optional(),
    promo: z.string().max(200).optional(),
    priceIndexMin: z.string().max(80).optional(),
    priceIndexMax: z.string().max(80).optional()
});

/**
 * Success
 */
export const zListOffersResponse = zOfferPage;

export const zListPoliciesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.uuid().optional()
});

export const zListPoliciesQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    scopes: z.enum([
        'ACCOUNT',
        'CATEGORY',
        'OFFER'
    ]).optional(),
    hasAssignments: z.enum(['YES', 'NO']).optional(),
    strategy: z.enum([
        'HOLD_PRICE',
        'TARGET_PROFITABILITY',
        'FOLLOW_COMPETITOR'
    ]).optional(),
    version: z.int().gte(0).lte(999999999).optional()
});

/**
 * Success
 */
export const zListPoliciesResponse = zPolicyPage;

export const zCreatePolicyBody = zPolicyRequest;

export const zCreatePolicyHeaders = z.object({
    'X-Organization-Id': z.string()
});

/**
 * Success
 */
export const zCreatePolicyResponse = zPolicy;

export const zListAssignmentsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListAssignmentsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListAssignmentsResponse = zAssignmentPage;

export const zCreateAssignmentBody = zAssignmentRequest;

export const zCreateAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Success
 */
export const zCreateAssignmentResponse = zAssignment;

export const zListCostRevisionsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCostRevisionsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListCostRevisionsResponse = zCostRevisionPage;

export const zCreateCostRevisionBody = zCostRequest;

export const zCreateCostRevisionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * OK
 */
export const zCreateCostRevisionResponse = zOperation;

export const zListAccrualsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListAccrualsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    component: z.string().max(128).optional()
});

/**
 * Success
 */
export const zListAccrualsResponse = zFinanceRecordPage;

export const zListPaymentsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListPaymentsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListPaymentsResponse = zPaymentPage;

export const zListSellerCostsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListSellerCostsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListSellerCostsResponse = zCostRevisionPage;

export const zCreateSellerCostBody = zCostRequest;

export const zCreateSellerCostHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * OK
 */
export const zCreateSellerCostResponse = zOperation;

export const zListReturnsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListReturnsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListReturnsResponse = zReturnRecordPage;

export const zListCalculationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCalculationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListCalculationsResponse = zEconomicsCalculationPage;

export const zListSalesPaceHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListSalesPaceQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListSalesPaceResponse = zSalesPacePage;

export const zListStocksHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListStocksQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    offerId: z.string().max(512).optional(),
    warehouse: z.string().max(512).optional(),
    physicalMin: z.string().max(512).optional(),
    physicalMax: z.string().max(512).optional(),
    availableMin: z.string().max(512).optional(),
    availableMax: z.string().max(512).optional(),
    reservedMin: z.string().max(512).optional(),
    reservedMax: z.string().max(512).optional(),
    warehouseId: z.uuid().optional()
});

/**
 * Success
 */
export const zListStocksResponse = zStockPage;

export const zListCompetitorsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCompetitorsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    sort: z.enum([
        'product',
        'seller',
        'price',
        'delivery',
        'observedAt',
        'status',
        'id',
        'segment',
        'inStock',
        'date'
    ]).optional().default('observedAt'),
    status: z.enum(['ACTIVE', 'REVOKED']).optional(),
    offerId: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    sourceId: z.uuid().optional(),
    segment: z.string().max(1000).optional()
});

/**
 * Success
 */
export const zListCompetitorsResponse = zCompetitorObservationPage;

export const zCreateCompetitorBody = zCompetitorRequest;

export const zCreateCompetitorHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Success
 */
export const zCreateCompetitorResponse = zCompetitorObservation;

export const zListMembershipsHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zListMembershipsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListMembershipsResponse = zMembershipPage;

export const zListAccountAccessHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListAccountAccessQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListAccountAccessResponse = zAccountAccessPage;

export const zListAuditHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zListAuditQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListAuditResponse = zAuditRecordPage;

export const zListOperationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

export const zListOperationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListOperationsResponse = zBackgroundOperationPage;

export const zListImportsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListImportsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc'),
    kind: z.string().max(128).optional()
});

/**
 * Success
 */
export const zListImportsResponse = zImportSummaryPage;

export const zUploadImportBody = z.object({
    file: z.string(),
    kind: z.enum([
        'COSTS',
        'SELLER_COSTS',
        'TAX',
        'PRICE_PARAMETERS',
        'COMPETITORS'
    ]),
    clientRequestId: z.string(),
    expectedRevision: z.int(),
    delimiter: z.enum(['SEMICOLON', 'COMMA']).default('SEMICOLON'),
    decimalSeparator: z.enum(['DOT', 'COMMA']).default('DOT'),
    sheetName: z.string().max(128).optional()
});

export const zUploadImportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zUploadImportResponse = zOperation;

export const zListReportsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

export const zListReportsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListReportsResponse = zReportSummaryPage;

export const zCreateReportBody = zReportRequest;

export const zCreateReportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zCreateReportResponse = zOperation;

export const zListNotificationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListNotificationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    offerId: z.string().optional(),
    policyId: z.string().optional(),
    category: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListNotificationsResponse = zNotificationPage;

export const zGetOfferHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetOfferPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetOfferResponse = zOffer;

export const zGetPolicyHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.uuid().optional()
});

export const zGetPolicyPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetPolicyResponse = zPolicy;

export const zGetDecisionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetDecisionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetDecisionResponse = zDecision;

export const zGetCommandHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetCommandPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetCommandResponse = zCommand;

export const zGetTemporaryRunHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetTemporaryRunPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetTemporaryRunResponse = zTemporaryRun;

export const zGetImportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetImportPath = z.object({
    id: z.string()
});

export const zGetImportQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zGetImportResponse = zImportDetail;

export const zListPolicyVersionsHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zListPolicyVersionsPath = z.object({
    id: z.string()
});

export const zListPolicyVersionsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(256).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    from: z.string().optional(),
    to: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Success
 */
export const zListPolicyVersionsResponse = zPolicyVersionPage;

export const zGetEconomicsSummaryHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetEconomicsSummaryQuery = z.object({
    period: z.string()
});

/**
 * Success
 */
export const zGetEconomicsSummaryResponse = zEconomicsSummary;

export const zGetSafetyEnvelopeHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Success
 */
export const zGetSafetyEnvelopeResponse = zSafetyEnvelope;

export const zSaveSafetyEnvelopeBody = zSafetyRequest;

export const zSaveSafetyEnvelopeHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Success
 */
export const zSaveSafetyEnvelopeResponse = zSafetyEnvelope;

export const zGetViewStateHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zGetViewStatePath = z.object({
    key: z.string()
});

/**
 * Success
 */
export const zGetViewStateResponse = zSavedView;

export const zSaveViewStateBody = zSavedViewRequest;

export const zSaveViewStateHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zSaveViewStatePath = z.object({
    key: z.string()
});

/**
 * Success
 */
export const zSaveViewStateResponse = zSavedView;

export const zResetViewStateBody = zMutation;

export const zResetViewStateHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zResetViewStatePath = z.object({
    key: z.string()
});

/**
 * Success
 */
export const zResetViewStateResponse = zSavedView;

export const zSavePolicyDraftBody = zPolicyRequest;

export const zSavePolicyDraftHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zSavePolicyDraftPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zSavePolicyDraftResponse = zPolicy;

export const zPublishPolicyBody = zMutation;

export const zPublishPolicyHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zPublishPolicyPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zPublishPolicyResponse = zPolicy;

export const zBulkAssignBody = zBulkAssignmentRequest;

export const zBulkAssignHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zBulkAssignResponse = zOperation;

export const zPauseAssignmentBody = zMutation;

export const zPauseAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zPauseAssignmentPath = z.object({
    id: z.string()
});

/**
 * Assignment state after the operation.
 */
export const zPauseAssignmentResponse = zAssignment;

export const zPreviewAssignmentBody = zMutation;

export const zPreviewAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zPreviewAssignmentPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zPreviewAssignmentResponse = zOperation;

export const zActivateAssignmentBody = zAutoActivationRequest;

export const zActivateAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zActivateAssignmentPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zActivateAssignmentResponse = zOperation;

export const zCreateTaxRevisionBody = zTaxRequest;

export const zCreateTaxRevisionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * OK
 */
export const zCreateTaxRevisionResponse = zOperation;

export const zUpdateCompetitorBody = zCompetitorRequest;

export const zUpdateCompetitorHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zUpdateCompetitorPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zUpdateCompetitorResponse = zCompetitorObservation;

export const zListInvitationsHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zListInvitationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    sort: z.string().max(128).optional(),
    status: z.string().optional(),
    direction: z.enum(['asc', 'desc']).optional().default('asc')
});

/**
 * Invitations
 */
export const zListInvitationsResponse = zInvitationPage;

export const zInviteMemberBody = zInvitationRequest;

export const zInviteMemberHeaders = z.object({
    'X-Organization-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zInviteMemberResponse = zInvitation;

export const zAcceptInvitationBody = zInvitationAccept;

/**
 * Success
 */
export const zAcceptInvitationResponse = zAcceptedInvitation;

export const zUpdateMembershipBody = zAccessRequest;

export const zUpdateMembershipHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zUpdateMembershipPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zUpdateMembershipResponse = zMembership;

export const zRevokeMembershipBody = zMutation;

export const zRevokeMembershipHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zRevokeMembershipPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zRevokeMembershipResponse = zMembership;

export const zUpdateAccountAccessBody = zAccountAccessRequest;

export const zUpdateAccountAccessHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zUpdateAccountAccessPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zUpdateAccountAccessResponse = zAccountAccess;

export const zCreateSelectionBody = zSelectionRequest;

export const zCreateSelectionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

/**
 * Success
 */
export const zCreateSelectionResponse = zSelection;

export const zDownloadReportPath = z.object({
    id: z.string()
});

export const zDownloadReportQuery = z.object({
    organizationId: z.string(),
    accountId: z.string().optional()
});

/**
 * CSV stream; bounded server buffering
 */
export const zDownloadReportResponse = z.string();

export const zApplyImportBody = zImportApplyRequest;

export const zApplyImportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zApplyImportPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zApplyImportResponse = zOperation;

export const zDownloadImportErrorsPath = z.object({
    id: z.string()
});

export const zDownloadImportErrorsQuery = z.object({
    organizationId: z.string(),
    accountId: z.string()
});

/**
 * CSV stream
 */
export const zDownloadImportErrorsResponse = z.string();

export const zPreviewDecisionBody = zPreviewRequest;

export const zPreviewDecisionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zPreviewDecisionResponse = zOperation;

export const zPreviewFixedTargetBody = zFixedTargetRequest;

export const zPreviewFixedTargetHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zPreviewFixedTargetResponse = zOperation;

export const zApproveDecisionBody = zMutation;

export const zApproveDecisionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zApproveDecisionPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zApproveDecisionResponse = zOperation;

export const zReconcileCommandBody = zMutation;

export const zReconcileCommandHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zReconcileCommandPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zReconcileCommandResponse = zOperation;

export const zCancelCommandBody = zMutation;

export const zCancelCommandHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zCancelCommandPath = z.object({
    id: z.string()
});

/**
 * Cancelled
 */
export const zCancelCommandResponse = zCommand;

export const zListTemporaryRunsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListTemporaryRunsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    offerId: z.string().optional()
});

/**
 * Success
 */
export const zListTemporaryRunsResponse = zTemporaryRunPage;

export const zCreateTemporaryRunBody = zTemporaryRunRequest;

export const zCreateTemporaryRunHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Success
 */
export const zCreateTemporaryRunResponse = zOperation;

export const zGetTemporaryPermissionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetTemporaryPermissionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetTemporaryPermissionResponse = zTemporaryPermissionState;

export const zPermitTemporaryRunBody = zTemporaryPermissionRequest;

export const zPermitTemporaryRunHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zPermitTemporaryRunPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zPermitTemporaryRunResponse = zEconomicPermission;

export const zFinishTemporaryRunBody = zMutation;

export const zFinishTemporaryRunHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zFinishTemporaryRunPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zFinishTemporaryRunResponse = zTemporaryRun;

export const zReadNotificationBody = zMutation;

export const zReadNotificationHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zReadNotificationPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zReadNotificationResponse = zNotification;

export const zReadAllNotificationsBody = zMutation;

export const zReadAllNotificationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zReadAllNotificationsResponse = zOperation;

export const zGetCurrentCostHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetCurrentCostPath = z.object({
    offerId: z.string()
});

/**
 * OK
 */
export const zGetCurrentCostResponse = zCostView;

export const zGetCurrentTaxHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * OK
 */
export const zGetCurrentTaxResponse = zTaxView;

export const zGetPauseStateHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetPauseStateQuery = z.object({
    offerId: z.string().optional()
});

/**
 * OK
 */
export const zGetPauseStateResponse = zPauseState;

export const zChangePauseBody = zPauseRequest;

export const zChangePauseHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * OK
 */
export const zChangePauseResponse = zPauseState;

export const zDisconnectConnectionBody = zMutation;

export const zDisconnectConnectionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zDisconnectConnectionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zDisconnectConnectionResponse = zConnectionView;

export const zChangePolicyStatusBody = zPolicyStatusRequest;

export const zChangePolicyStatusHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zChangePolicyStatusPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zChangePolicyStatusResponse = zPolicy;

export const zGetOperationHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

export const zGetOperationPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetOperationResponse = zBackgroundOperation;

export const zGetOfferBoundsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetOfferBoundsPath = z.object({
    offerId: z.uuid()
});

/**
 * Success
 */
export const zGetOfferBoundsResponse = zOfferBounds;

export const zSaveOfferBoundsBody = zOfferBoundsRequest;

export const zSaveOfferBoundsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zSaveOfferBoundsPath = z.object({
    offerId: z.uuid()
});

export const zSaveOfferBoundsResponse = z.union([
    zOfferBounds,
    zSafetyEnvelope
]);

export const zListPlacementsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListPlacementsPath = z.object({
    id: z.uuid()
});

export const zListPlacementsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zListPlacementsResponse = zPlacementPage;

export const zSyncHistoryBody = zHistorySyncRequest;

export const zSyncHistoryHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zSyncHistoryPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zSyncHistoryResponse = zOperation;

export const zSyncReportsBody = zReportSyncRequest;

export const zSyncReportsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zSyncReportsPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zSyncReportsResponse = zOperation;

export const zReissueInvitationBody = zMutation;

export const zReissueInvitationHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zReissueInvitationPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zReissueInvitationResponse = zInvitation;

export const zRevokeInvitationBody = zMutation;

export const zRevokeInvitationHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zRevokeInvitationPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zRevokeInvitationResponse = zInvitation;

export const zReactivateMembershipBody = zMutation;

export const zReactivateMembershipHeaders = z.object({
    'X-Organization-Id': z.string()
});

export const zReactivateMembershipPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zReactivateMembershipResponse = zMembership;

export const zRevokeAccountAccessBody = zMutation;

export const zRevokeAccountAccessHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zRevokeAccountAccessPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zRevokeAccountAccessResponse = zAccountAccess;

export const zGetReportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string().optional()
});

export const zGetReportPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetReportResponse = zReportSummary;

export const zGetAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetAssignmentPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetAssignmentResponse = zAssignment;

export const zGetAutoGrantHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetAutoGrantPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetAutoGrantResponse = zAutoGrantState;

export const zRevokeAutoGrantBody = zMutation;

export const zRevokeAutoGrantHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zRevokeAutoGrantPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zRevokeAutoGrantResponse = zAutoGrantState;

export const zRevokeTemporaryPermissionBody = zPermissionRevocationRequest;

export const zRevokeTemporaryPermissionHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zRevokeTemporaryPermissionPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zRevokeTemporaryPermissionResponse = zTemporaryRun;

export const zPreviewAutoHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zPreviewAutoPath = z.object({
    id: z.string()
});

export const zPreviewAutoQuery = z.object({
    expectedRevision: z.int().gte(1)
});

/**
 * Success
 */
export const zPreviewAutoResponse = zAutoActivationReview;

export const zListQuantityComparisonsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListQuantityComparisonsPath = z.object({
    id: z.string()
});

export const zListQuantityComparisonsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zListQuantityComparisonsResponse = zQuantityComparisonPage;

export const zCompareQuantityBody = zQuantityRequest;

export const zCompareQuantityHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zCompareQuantityPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zCompareQuantityResponse = zQuantityComparison;

export const zRevalidateImportBody = zMutation;

export const zRevalidateImportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zRevalidateImportPath = z.object({
    id: z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zRevalidateImportResponse = zOperation;

export const zCancelImportBody = zImportApplyRequest;

export const zCancelImportHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zCancelImportPath = z.object({
    id: z.string()
});

/**
 * Cancelled
 */
export const zCancelImportResponse = z.void();

export const zRefreshSalesPaceBody = z.object({
    clientRequestId: z.uuid()
});

export const zRefreshSalesPaceHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Accepted; execution is tracked separately.
 */
export const zRefreshSalesPaceResponse = zOperation;

export const zGetAssignmentBatchHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetAssignmentBatchPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetAssignmentBatchResponse = zAssignmentBatch;

export const zListAssignmentBatchRowsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListAssignmentBatchRowsPath = z.object({
    id: z.string()
});

export const zListAssignmentBatchRowsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zListAssignmentBatchRowsResponse = zAssignmentBatchRowPage;

/**
 * Обе сессии завершены
 */
export const zLogoutResponse = zLogoutResult;

export const zReviewTemporaryRunBody = zTemporaryRunReviewRequest;

export const zReviewTemporaryRunHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

/**
 * Проверенная область завершения
 */
export const zReviewTemporaryRunResponse = zTemporaryRunCompletionReview;

export const zListCampaignsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCampaignsPath = z.object({
    id: z.string()
});

export const zListCampaignsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zListCampaignsResponse = zCampaignPage;

export const zGetSupplierPriceIndicesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zGetSupplierPriceIndicesPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zGetSupplierPriceIndicesResponse = zSupplierPriceIndices;

export const zResumeAssignmentBody = zMutation;

export const zResumeAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zResumeAssignmentPath = z.object({
    id: z.string()
});

/**
 * Assignment state after the operation.
 */
export const zResumeAssignmentResponse = zAssignment;

export const zListCompetitorSourcesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCompetitorSourcesQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional()
});

/**
 * Success
 */
export const zListCompetitorSourcesResponse = zCompetitorSourcePage;

export const zRevokeCompetitorBody = zMutation;

export const zRevokeCompetitorHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zRevokeCompetitorPath = z.object({
    id: z.string()
});

/**
 * Success
 */
export const zRevokeCompetitorResponse = zCompetitorObservation;

export const zListReservationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListReservationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    offerId: z.uuid().optional(),
    poolId: z.uuid().optional()
});

/**
 * Success
 */
export const zListReservationsResponse = zQuantityReservationPage;

export const zListObligationsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListObligationsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    offerId: z.uuid().optional(),
    poolId: z.uuid().optional()
});

/**
 * Success
 */
export const zListObligationsResponse = zQuantityObligationPage;

export const zListPromotionsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListPromotionsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional()
});

/**
 * Success
 */
export const zListPromotionsResponse = zPromotionPage;

export const zListCategoriesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListCategoriesQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional(),
    parentId: z.uuid().optional()
});

/**
 * Success
 */
export const zListCategoriesResponse = zCategoryPage;

export const zListWarehousesHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListWarehousesQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50),
    search: z.string().max(200).optional()
});

/**
 * Success
 */
export const zListWarehousesResponse = zWarehousePage;

export const zReviewAssignmentDetachHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zReviewAssignmentDetachPath = z.object({
    id: z.string()
});

export const zReviewAssignmentDetachQuery = z.object({
    expectedRevision: z.int().gte(1)
});

/**
 * Success
 */
export const zReviewAssignmentDetachResponse = zAssignmentDetachReview;

export const zDetachAssignmentBody = zAssignmentDetachRequest;

export const zDetachAssignmentHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zDetachAssignmentPath = z.object({
    id: z.string()
});

/**
 * Assignment state after the operation.
 */
export const zDetachAssignmentResponse = zAssignment;

export const zListAutomationSweepsHeaders = z.object({
    'X-Organization-Id': z.string(),
    'X-Account-Id': z.string()
});

export const zListAutomationSweepsQuery = z.object({
    page: z.int().gte(0).optional().default(0),
    size: z.int().gte(1).lte(200).optional().default(50)
});

/**
 * Success
 */
export const zListAutomationSweepsResponse = zAutomationSweepPage;
