import { readFile, writeFile } from 'node:fs/promises';
import { createClient } from '@hey-api/openapi-ts';
import config from '../openapi-ts.config.ts';

// The stock bundled transports emit `any`. Generate only the bounded JSON transport
// needed by this application, using the generator's types and runtime validators.
const specification = JSON.parse(await readFile('../backend/app/src/main/resources/openapi.yaml', 'utf8'));
await createClient(config);
const methods = [];
for (const [path, pathItem] of Object.entries(specification.paths)) {
  for (const [verb, operation] of Object.entries(pathItem)) {
    const id = operation.operationId;
    if (!id) continue;
    const type = id[0].toUpperCase() + id.slice(1);
    const success = Object.entries(operation.responses).find(([status]) => /^2\d\d$/.test(status))?.[1];
    const binary = Boolean(success.content?.['text/csv']);
    const form = operation.requestBody?.content?.['multipart/form-data'];
    const hasPath = operation.parameters.some(parameter => parameter.in === 'path');
    const hasQuery = operation.parameters.some(parameter => parameter.in === 'query');
    const required = Boolean(operation.requestBody) || hasPath || operation.parameters.some(parameter => parameter.in === 'query' && parameter.required);
    const url = '/api/v1' + path.replace(/\{([^}]+)\}/g, (_, key) => '${encodeURIComponent(params.path.' + key + ')}');
    let body = '';
    if (form) {
      body = 'const body = new FormData();\n';
      for (const name of Object.keys(form.schema.properties)) {
        body += `    ${form.schema.required.includes(name)?'':`if(params.body.${name}!==undefined)`}body.append('${name}', ${name === 'file' ? 'params.body.file' : 'String(params.body.' + name + ')'});\n`;
      }
    }
    methods.push(`  async ${id}(params: Omit<T.${type}Data, 'headers'|'url'>${required?'':' = {}'}, scope?: RequestScope): Promise<${binary?'Blob':'T.'+type+'Response'}> {
    ${body}const response = await firstValueFrom(this.http.request(${JSON.stringify(verb.toUpperCase())}, \`${url}\`, {
      ${operation.requestBody?'body: '+(form?'body':'params.body')+',':''}
      ${hasQuery?'params: queryParameters(params.query),':''}
      headers: contextHeaders(scope, ${!operation.parameters.some(parameter=>parameter.name==='X-Account-Id')&&operation.parameters.some(parameter=>parameter.name==='X-Organization-Id')&&id!=='getMe'}), responseType: '${binary?'blob':'json'}', timeout: ${id.includes('ViewState')?'15_000':'30_000'},
    }));
    return ${binary?'response':`Z.z${type}Response.parse(response)`};
  }`);
  }
}
await writeFile('src/app/api/angular-client.gen.ts', `// Generated by npm run generate:api from the canonical OpenAPI contract. Do not edit.
import { HttpClient, HttpHeaders, HttpParams } from '@angular/common/http';
import { inject } from '@angular/core';
import { firstValueFrom } from 'rxjs';
import type * as T from './types.gen';
import * as Z from './zod.gen';

export interface RequestScope {organizationId:string;accountId?:string;}
function contextHeaders(scope:RequestScope|undefined,organizationOnly:boolean):HttpHeaders {
  let headers=new HttpHeaders();
  if(scope){headers=headers.set('X-Organization-Id',scope.organizationId);headers=headers.set('X-Account-Id',scope.accountId??'');}
  if(!scope&&organizationOnly)headers=headers.set('X-Account-Id','');
  return headers;
}

function queryParameters(query?: Record<string,string|number|boolean|undefined>): HttpParams {
  let params = new HttpParams();
  for (const [name,value] of Object.entries(query ?? {})) {
    if (value !== undefined) params = params.set(name,value);
  }
  return params;
}

export abstract class GeneratedApiClient {
  private readonly http = inject(HttpClient);
${methods.join('\n\n')}
}
`);
