import { Component, input } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NonCompetitiveRule, Rule, Strategy } from '../core/models';

export function emptyRule():NonCompetitiveRule{return{strategy:'HOLD_PRICE',priceKind:'BASE_SELLER',target:'',corridorMinimum:null,corridorMaximum:null,metric:null,unreachable:'KEEP_SAFE',competitor:null,reserve:null,promoMode:'PRESERVE',selectedPromos:[],protectedPromos:[]};}

@Component({selector:'app-rule-editor',imports:[FormsModule],template:`
  <div class="fields-2"><label class="field">Способ выбора цены<select [ngModel]="rule().strategy" (ngModelChange)="strategy($event)" [ngModelOptions]="{standalone:true}"><option value="HOLD_PRICE">Удержание цены</option><option value="TARGET_PROFITABILITY">Целевая прибыльность</option>@if(!reserve()){<option value="FOLLOW_COMPETITOR">Следование конкуренту</option>}</select></label><label class="field">Вид цены<select [(ngModel)]="rule().priceKind" [ngModelOptions]="{standalone:true}"><option value="BASE_SELLER">Обычная цена продавца</option><option value="EFFECTIVE_SELLER">Эффективная цена продавца</option><option value="BUYER_TOTAL">Полная цена покупателя</option></select></label></div>
  @if(rule().strategy!=='FOLLOW_COMPETITOR'){<div class="fields-2">@if(rule().strategy==='TARGET_PROFITABILITY'){<label class="field">Показатель<select [(ngModel)]="rule().metric" [ngModelOptions]="{standalone:true}"><option value="PROFIT">Прибыль, ₽</option><option value="MARGIN">Маржа, доля</option></select></label>}<label class="field">Цель {{rule().metric==='MARGIN'?'(доля от 0 до 1)':'(₽)'}}<input inputmode="decimal" [(ngModel)]="rule().target" [ngModelOptions]="{standalone:true}" required pattern="[0-9]+(\\.[0-9]+)?"></label></div>}
  @if(rule().strategy==='HOLD_PRICE'){<div class="fields-2"><label class="field">Нижняя граница коридора, ₽<input inputmode="decimal" [(ngModel)]="rule().corridorMinimum" [ngModelOptions]="{standalone:true}" required pattern="[0-9]+(\\.[0-9]+)?"></label><label class="field">Верхняя граница коридора, ₽<input inputmode="decimal" [(ngModel)]="rule().corridorMaximum" [ngModelOptions]="{standalone:true}" required pattern="[0-9]+(\\.[0-9]+)?"></label></div>}
  <label class="field">Если цель недостижима<select [(ngModel)]="rule().unreachable" [ngModelOptions]="{standalone:true}"><option value="KEEP_SAFE">Сохранить безопасную текущую цену</option><option value="NEAREST_SAFE">Выбрать ближайшую безопасную цену</option></select></label>
  @if(rule().competitor;as competitor){<div class="form-section"><h4>Сопоставимый ориентир</h4><div class="fields-2"><label class="field">Агрегация<select [(ngModel)]="competitor.aggregation" [ngModelOptions]="{standalone:true}"><option value="SELECTED_SELLER">Выбранный продавец</option><option value="MIN">Минимум</option><option value="SECOND">Вторая цена</option><option value="MEDIAN">Медиана</option><option value="MEAN">Среднее</option></select></label><label class="field">Минимум источников<input type="number" min="1" max="100" [(ngModel)]="competitor.minimumSources" [ngModelOptions]="{standalone:true}" required></label></div>@if(competitor.aggregation==='SELECTED_SELLER'){<p class="inline-note">Продавец выбирается отдельно в назначении кабинета.</p>}<label class="field">Сегмент сопоставимости<input [(ngModel)]="competitor.segment" [ngModelOptions]="{standalone:true}" required></label><div class="fields-2"><label class="field">Смещение, ₽<input inputmode="decimal" [(ngModel)]="competitor.amountOffset" (ngModelChange)="competitor.ratioOffset=null" [ngModelOptions]="{standalone:true}"></label><label class="field">Смещение, доля<input inputmode="decimal" [(ngModel)]="competitor.ratioOffset" (ngModelChange)="competitor.amountOffset=null" [ngModelOptions]="{standalone:true}"></label><label class="field">Допуск цены, ₽<input inputmode="decimal" [(ngModel)]="competitor.tolerance" [ngModelOptions]="{standalone:true}" required></label><label class="field">Давность, секунд<input type="number" min="1" [(ngModel)]="competitor.maxAgeSeconds" [ngModelOptions]="{standalone:true}" required></label></div><label class="option-line"><input type="checkbox" [checked]="!!rule().reserve" (change)="toggleReserve()">Резервное правило при отсутствии ориентира</label>@if(rule().reserve;as fallback){<app-rule-editor [rule]="fallback" [reserve]="true" />}</div>}
  <label class="field">Работа с акциями<select [(ngModel)]="rule().promoMode" [ngModelOptions]="{standalone:true}"><option value="PRESERVE">Сохранить текущее участие</option><option value="CONSIDER">Учитывать допустимые акции</option><option value="ENSURE_SELECTED">Обеспечить выбранное участие</option><option value="FORBID_SELECTED">Исключить выбранное участие</option></select></label><p class="inline-note">Выбранные и защищённые акции задаются в назначении кабинета.</p>
`})
export class RuleEditorComponent {
  readonly rule=input.required<Rule>();readonly reserve=input(false);
  strategy(value:Strategy):void{const rule=this.rule();if(rule.strategy===value)return;rule.strategy=value;rule.metric=value==='TARGET_PROFITABILITY'?'PROFIT':null;rule.target=value==='FOLLOW_COMPETITOR'?null:'';rule.corridorMinimum=null;rule.corridorMaximum=null;rule.competitor=value==='FOLLOW_COMPETITOR'?{aggregation:'MIN',selectedSource:null,minimumSources:1,segment:'',amountOffset:'0',ratioOffset:null,tolerance:'0',maxAgeSeconds:3600}:null;rule.reserve=null;}
  toggleReserve():void{this.rule().reserve=this.rule().reserve?null:emptyRule();}
  ids(value:string):string[]{return value.split(',').map(item=>item.trim()).filter(Boolean);}
}
